import { NextResponse } from "next/server";
import { sendTransactionalEmail } from "@/lib/email/send";
import { createAdminClient } from "@/lib/supabase/admin";

type Alert={key:string;type:"overdue_task"|"low_stock"|"expiration"|"calibration";entityType:string;entityId:string;title:string;detail:string};
const escapeHtml=(value:string)=>value.replace(/[&<>'"]/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[character]??character);
function periodKey(frequency:string){const now=new Date();if(frequency==="weekly"){const start=new Date(Date.UTC(now.getUTCFullYear(),0,1));return `${now.getUTCFullYear()}-W${Math.ceil((((now.getTime()-start.getTime())/86400000)+start.getUTCDay()+1)/7)}`;}return now.toISOString().slice(0,10);}

export async function POST(request:Request){const secret=process.env.CRON_SECRET;if(!secret||request.headers.get("authorization")!==`Bearer ${secret}`)return NextResponse.json({error:"Unauthorized"},{status:401});const admin=createAdminClient();const preferences=await admin.from("notification_preferences").select("organization_id,user_id,email,overdue_tasks,low_stock,expirations,calibration,lead_days,digest_frequency").neq("digest_frequency","off").limit(250);if(preferences.error)return NextResponse.json({error:"Preferences unavailable"},{status:500});let sent=0,skipped=0;
  for(const preference of preferences.data??[]){const today=new Date().toISOString().slice(0,10),threshold=new Date(Date.now()+preference.lead_days*86400000).toISOString().slice(0,10);const alerts:Alert[]=[];const [tasks,inventory,equipment,organization]=await Promise.all([
    preference.overdue_tasks?admin.from("lab_tasks").select("id,title,due_date").eq("organization_id",preference.organization_id).neq("status","completed").lt("due_date",today).is("deleted_at",null).limit(50):Promise.resolve({data:[],error:null}),
    admin.from("inventory_items").select("id,code,name,quantity,minimum_stock,expiration_date").eq("organization_id",preference.organization_id).is("deleted_at",null).limit(250),
    preference.calibration?admin.from("equipment").select("id,code,name,status,next_calibration").eq("organization_id",preference.organization_id).is("deleted_at",null).or(`status.eq.calibration_required,next_calibration.lte.${threshold}`).limit(50):Promise.resolve({data:[],error:null}),
    admin.from("organizations").select("name").eq("id",preference.organization_id).single(),
  ]);if(tasks.error||inventory.error||equipment.error||organization.error){skipped++;continue;}
  for(const task of tasks.data??[])alerts.push({key:`overdue_task:${task.id}:${periodKey(preference.digest_frequency)}`,type:"overdue_task",entityType:"Task",entityId:task.id,title:task.title,detail:`Due ${task.due_date}`});
  for(const item of inventory.data??[]){if(preference.low_stock&&Number(item.quantity)<=Number(item.minimum_stock))alerts.push({key:`low_stock:${item.id}:${periodKey(preference.digest_frequency)}`,type:"low_stock",entityType:"Inventory item",entityId:item.id,title:`${item.code} · ${item.name}`,detail:`${item.quantity} remaining; minimum ${item.minimum_stock}`});if(preference.expirations&&item.expiration_date&&item.expiration_date<=threshold)alerts.push({key:`expiration:${item.id}:${periodKey(preference.digest_frequency)}`,type:"expiration",entityType:"Inventory item",entityId:item.id,title:`${item.code} · ${item.name}`,detail:`Expires ${item.expiration_date}`});}
  for(const item of equipment.data??[])alerts.push({key:`calibration:${item.id}:${periodKey(preference.digest_frequency)}`,type:"calibration",entityType:"Equipment",entityId:item.id,title:`${item.code} · ${item.name}`,detail:item.next_calibration?`Calibration due ${item.next_calibration}`:"Calibration required"});
  if(!alerts.length){skipped++;continue;}const delivered=await admin.from("notification_deliveries").select("alert_key").eq("organization_id",preference.organization_id).eq("user_id",preference.user_id).in("alert_key",alerts.map(alert=>alert.key));if(delivered.error){skipped++;continue;}const existing=new Set((delivered.data??[]).map(row=>row.alert_key)),fresh=alerts.filter(alert=>!existing.has(alert.key));if(!fresh.length){skipped++;continue;}const text=fresh.map(alert=>`• ${alert.title}: ${alert.detail}`).join("\n"),html=fresh.map(alert=>`<li style="margin:0 0 10px"><strong>${escapeHtml(alert.title)}</strong><br><span style="color:#64748b">${escapeHtml(alert.detail)}</span></li>`).join("");try{await sendTransactionalEmail(preference.email,{subject:`${fresh.length} LabOps action${fresh.length===1?"":"s"} for ${organization.data.name}`,text:`MicroCD LabOps action digest\n\n${text}\n\nOpen LabOps: ${process.env.NEXT_PUBLIC_SITE_URL??"https://labops.microcdlabs.com"}/app`,html:`<div style="font-family:Arial,sans-serif;max-width:600px;color:#172033"><p style="font-size:12px;font-weight:700;color:#0f766e">MICROCD LABOPS</p><h1 style="font-size:24px">Action digest</h1><p>${fresh.length} item${fresh.length===1?"":"s"} need attention in ${escapeHtml(organization.data.name)}.</p><ul style="padding-left:20px">${html}</ul><p><a href="${process.env.NEXT_PUBLIC_SITE_URL??"https://labops.microcdlabs.com"}/app" style="display:inline-block;background:#0f766e;color:white;padding:12px 18px;border-radius:6px;text-decoration:none;font-weight:700">Open LabOps</a></p></div>`});const delivery=await admin.from("notification_deliveries").insert(fresh.map(alert=>({organization_id:preference.organization_id,user_id:preference.user_id,alert_key:alert.key,alert_type:alert.type,entity_type:alert.entityType,entity_id:alert.entityId})));if(delivery.error)throw delivery.error;sent++;}catch{skipped++;}}
  return NextResponse.json({status:"ok",digestsSent:sent,preferencesSkipped:skipped,checkedAt:new Date().toISOString()},{headers:{"Cache-Control":"no-store"}});
}
