import { marketingMetadata } from "@/lib/seo";

export const metadata = marketingMetadata({
  title: "AI Use Disclosure",
  description: "How optional AI-assisted drafting works in MicroCD LabOps, including evidence boundaries, labeling, and required human review.",
  path: "/legal/ai-use",
});

export default function AiUsePage(){return <article className="prose-legal mx-auto max-w-4xl px-5 py-16"><h1 className="text-4xl font-semibold">AI Use Disclosure</h1><p>AI assistance is optional and disabled without administrator configuration. Generated text is labeled AI-assisted, may contain errors or omissions, and must be verified against source evidence before use.</p><h2>Quality documents</h2><p>Quality Document Studio uses a private-template mode. The AI service receives only public template metadata such as document type, lifecycle phase, regulatory basis, and section names. Project names, draft content, files, evidence, and identifiers are not transmitted. The result is a generic rough template with missing information marked for completion.</p><h2>Engineering reports</h2><p>Report drafting can receive selected report text only after a user explicitly authorizes that request. A data-loss-prevention scan blocks detected credentials and redacts common personal and medical identifiers before transmission. Detection reduces risk but cannot guarantee that all sensitive information will be identified.</p><h2>Retention and human control</h2><p>Requests use the configured AI provider with response storage disabled where supported. Provider abuse-monitoring retention may still apply unless the customer has separately qualified for stronger data controls. AI cannot determine acceptance criteria, approve reports, sign records, or replace technical, quality, or regulatory review.</p></article>}
