import OpenAI from "openai";
import {NextResponse} from "next/server";
import {z} from "zod";
import {getWorkspaceIdentity} from "@/lib/auth";
import {appConfig} from "@/lib/config";
import {catalogItem} from "@/lib/quality-documents/catalog";
import {can} from "@/lib/security/permissions";
import {dlpSummary,scanAndSanitize} from "@/lib/security/dlp";
import {enforceRateLimit} from "@/lib/security/rate-limit";
import {createAdminClient} from "@/lib/supabase/admin";

const schema=z.object({documentId:z.string().uuid(),localContent:z.string().max(50000).default("")});

export async function POST(request:Request){
  const identity=await getWorkspaceIdentity();if(!identity)return NextResponse.json({error:"Authentication required"},{status:401});if(identity.demo||!can(identity.role,"lab:write"))return NextResponse.json({error:"AI document enhancement is unavailable for this workspace"},{status:403});if(!appConfig.aiConfigured)return NextResponse.json({error:"AI assistance is disabled until configured"},{status:503});
  const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid document enhancement request"},{status:400});const localScan=scanAndSanitize(parsed.data.localContent);if(localScan.blocked)return NextResponse.json({error:"A secret or credential was detected in the local draft. It was not sent anywhere. Remove or rotate it before continuing.",dlp:dlpSummary(localScan)},{status:422});
  const admin=createAdminClient();const [organization,document]=await Promise.all([admin.from("organizations").select("ai_enabled,ai_monthly_limit").eq("id",identity.organizationId).single(),admin.from("quality_documents").select("id,title,document_key,status,regulatory_basis,applicability,lifecycle_phase,quality_file").eq("id",parsed.data.documentId).eq("organization_id",identity.organizationId).maybeSingle()]);if(organization.error||!organization.data?.ai_enabled)return NextResponse.json({error:"AI assistance is not enabled by this organization"},{status:403});if(document.error||!document.data)return NextResponse.json({error:"Quality document not found"},{status:404});if(["in_review","approved","obsolete"].includes(document.data.status))return NextResponse.json({error:"This controlled document is locked"},{status:409});
  const monthStart=new Date();monthStart.setUTCDate(1);monthStart.setUTCHours(0,0,0,0);const usage=await admin.from("ai_usage").select("id",{count:"exact",head:true}).eq("organization_id",identity.organizationId).gte("created_at",monthStart.toISOString());if((usage.count??0)>=organization.data.ai_monthly_limit)return NextResponse.json({error:"Monthly AI usage limit reached"},{status:429});const rate=await enforceRateLimit(`${identity.organizationId}:${identity.userId}`,"ai_quality_document",15,3600);if(!rate.allowed)return NextResponse.json({error:"AI request limit reached. Try again later."},{status:429});
  const item=catalogItem(document.data.document_key);if(!item)return NextResponse.json({error:"Document template is unavailable"},{status:409});const model=process.env.OPENAI_MODEL??"gpt-5.6-terra",promptVersion="quality-private-template-v1",client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
  try{const response=await client.responses.create({model,store:false,reasoning:{effort:"none"},text:{verbosity:"medium"},max_output_tokens:3000,instructions:"Create a generic, editable medical-device quality-document template. Do not assert compliance or supply project-specific facts. Every factual field, decision, date, result, citation, approval, and responsible person must be marked [TBD]. Keep regulatory basis separate from evidence. Return Markdown only. This is an AI-assisted rough template requiring author editing and independent human review.",input:`Public template metadata only.\nDocument type: ${item.title}\nLifecycle phase: ${item.phase} — ${item.phaseName}\nRecord grouping: ${item.qualityFile}\nRegulatory basis: ${item.basis}\nApplicability: ${item.applicability}\nRequired headings: ${item.sections.join("; ")}`});const inputTokens=response.usage?.input_tokens??0,outputTokens=response.usage?.output_tokens??0,inputRate=Number(process.env.OPENAI_INPUT_COST_PER_MILLION??0),outputRate=Number(process.env.OPENAI_OUTPUT_COST_PER_MILLION??0);await admin.from("ai_usage").insert({organization_id:identity.organizationId,user_id:identity.userId,quality_document_id:document.data.id,prompt_version:promptVersion,model,input_tokens:inputTokens,output_tokens:outputTokens,estimated_cost_usd:(inputTokens*inputRate+outputTokens*outputRate)/1_000_000});return NextResponse.json({suggestion:response.output_text,source:"ai-assisted",requiresHumanAcceptance:true,promptVersion,model,generatedAt:new Date().toISOString(),dlp:dlpSummary(localScan),privacyMode:"public-metadata-only"},{headers:{"Cache-Control":"private, no-store"}});
  }catch{await admin.from("operational_events").insert({correlation_id:crypto.randomUUID(),organization_id:identity.organizationId,category:"ai",severity:"error",code:"ai_quality_document_failed",safe_message:"AI quality-document request failed"});return NextResponse.json({error:"AI document enhancement is temporarily unavailable"},{status:502});}
}
