import { Braces, Download, ExternalLink, KeyRound, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { requireWorkspaceIdentity } from "@/lib/auth";
import { appConfig } from "@/lib/config";
import { can } from "@/lib/security/permissions";

const resources=[{key:"experiments",label:"Experiments"},{key:"samples",label:"Samples"},{key:"inventory",label:"Inventory"},{key:"equipment",label:"Equipment"}];
export default async function DevelopersPage(){const identity=await requireWorkspaceIdentity();const exportAllowed=can(identity.role,"workspace:export");return <><PageHeader eyebrow="Customer-controlled data" title="Exports & API" description="Take organization data out in useful formats and integrate read-only LabOps records without sharing service credentials." actions={<Badge tone="good">Organization scoped</Badge>}/><div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><Card><CardHeader title="CSV exports" description="Up to 5,000 current records per resource. Soft-deleted records are excluded."/><CardContent className="grid gap-3 sm:grid-cols-2">{resources.map(resource=><ButtonLink key={resource.key} href={`/api/v1/export/${resource.key}`} variant="secondary" className={!exportAllowed?"pointer-events-none opacity-50":""}><Download size={16}/>{resource.label}</ButtonLink>)}{!exportAllowed?<p className="col-span-full text-xs text-slate-500">Only owners and administrators can export workspace data.</p>:null}</CardContent></Card><Card><CardHeader title="Read-only API" description="Use a signed-in Supabase access token. Results are always restricted to the user’s active organization."/><CardContent><div className="flex gap-3 rounded-lg border border-sky-200 bg-sky-50 p-4"><ShieldCheck className="mt-0.5 shrink-0 text-sky-700" size={18}/><p className="text-sm leading-6 text-sky-900">Never use the Supabase service-role key in client code or integrations. Access tokens inherit membership and role boundaries.</p></div><div className="mt-5 rounded-lg bg-slate-950 p-4 text-sm text-slate-100"><code className="break-all">curl -H &quot;Authorization: Bearer $LABOPS_ACCESS_TOKEN&quot; &quot;{appConfig.siteUrl}/api/v1/experiments?limit=25&quot;</code></div><div className="mt-4 flex flex-wrap gap-3"><ButtonLink href="/api/v1/openapi" variant="secondary" external><Braces size={16}/>OpenAPI specification <ExternalLink size={13}/></ButtonLink></div></CardContent></Card></div><Card className="mt-5"><CardHeader title="Available endpoints" description="Versioned under /api/v1 so integrations can evolve predictably."/><CardContent className="grid gap-3 md:grid-cols-2">{resources.map(resource=><div key={resource.key} className="rounded-lg border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><strong className="text-slate-950">GET /api/v1/{resource.key}</strong><KeyRound size={16} className="text-slate-400"/></div><p className="mt-2 text-sm text-slate-600">Supports limit, offset, status, and q parameters. Maximum page size: 100.</p></div>)}</CardContent></Card></>}
