import { CheckCircle2, ShieldCheck } from "lucide-react";
import { CsvImportPanel } from "@/components/app/csv-import-panel";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { requireWorkspaceIdentity } from "@/lib/auth";
import { listProjects } from "@/lib/data/workspace";
import { importExperimentsCsv, importInventoryCsv } from "../growth-actions";

export default async function ImportsPage({searchParams}:{searchParams:Promise<{inventory?:string;experiments?:string}>}){const identity=await requireWorkspaceIdentity();const params=await searchParams;const projects=await listProjects(identity);return <><PageHeader eyebrow="Move beyond spreadsheets" title="CSV imports" description="Preview and validate structured records before committing them to your organization-scoped workspace." actions={<Badge tone="info">250 rows per import</Badge>}/>{params.inventory||params.experiments?<div className="mb-5 flex items-start gap-3 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-emerald-900"><CheckCircle2 className="mt-0.5" size={18}/><div><strong>Import completed</strong><p className="mt-1 text-sm">{params.inventory?`${params.inventory} inventory items were added with opening receipt transactions.`:`${params.experiments} experiments were added to the selected project.`}</p></div></div>:null}<Card className="mb-5"><CardContent className="flex gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-teal-700" size={19}/><p className="text-sm leading-6 text-slate-600"><strong className="text-slate-950">Safe import behavior:</strong> the entire file is validated first, duplicate identifiers stop the import, inventory opening balances create immutable receipt transactions, and every completed import is recorded in activity and pilot analytics.</p></CardContent></Card><div className="grid gap-5 xl:grid-cols-2"><CsvImportPanel title="Import experiments" description="Use one destination project and create draft or planned experiments from an existing study spreadsheet." requiredHeaders={["title","objective","experiment_type"]} templateHref="/templates/experiment-import.csv" action={importExperimentsCsv} projects={projects.map(project=>({id:project.id,label:`${project.code} · ${project.name}`}))}/><CsvImportPanel title="Import inventory" description="Bring reagents and consumables into stock control without losing the history of their opening balances." requiredHeaders={["code","name"]} templateHref="/templates/inventory-import.csv" action={importInventoryCsv}/></div></>}
