"use server";

import Papa from "papaparse";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireWorkspaceIdentity } from "@/lib/auth";
import { experimentImportRowSchema, inventoryImportRowSchema, workspaceTemplates } from "@/lib/growth-capabilities";
import { can, type Permission } from "@/lib/security/permissions";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

function textField(data:FormData,name:string){return String(data.get(name)??"").trim();}
async function context(permission:Permission){const identity=await requireWorkspaceIdentity();if(identity.demo)throw new Error("This capability is read-only in the fictional demo.");if(!can(identity.role,permission))throw new Error("You do not have permission to perform this action.");return {identity,supabase:await createClient()};}
async function csvRows(file:File){if(file.size>1_000_000)throw new Error("CSV files must be 1 MB or smaller.");const parsed=Papa.parse<Record<string,string>>(await file.text(),{header:true,skipEmptyLines:"greedy",transformHeader:(header)=>header.trim().toLowerCase().replaceAll(" ","_")});if(parsed.errors.length)throw new Error(`CSV could not be read near row ${parsed.errors[0].row??1}.`);if(!parsed.data.length||parsed.data.length>250)throw new Error("CSV imports must contain between 1 and 250 rows.");return parsed.data;}
async function event(organizationId:string,userId:string,eventName:string,entityType?:string,entityId?:string,metadata:Record<string,unknown>={}){const result=await createAdminClient().from("product_events").insert({organization_id:organizationId,actor_id:userId,event_name:eventName,entity_type:entityType??null,entity_id:entityId??null,metadata});if(result.error)throw new Error("The action completed, but adoption analytics could not be recorded.");}

export async function importInventoryCsv(formData:FormData){
  const {identity,supabase}=await context("lab:write");const file=formData.get("file");if(!(file instanceof File)||!file.name.toLowerCase().endsWith(".csv"))throw new Error("Choose an inventory CSV file.");const rows=await csvRows(file);
  const normalized=rows.map((row,index)=>{const result=inventoryImportRowSchema.safeParse({...row,item_type:row.item_type||"reagent",quantity:row.quantity||0,unit:row.unit||"each",minimum_stock:row.minimum_stock||0,manufacturer:row.manufacturer||"",catalog_number:row.catalog_number||"",lot_number:row.lot_number||"",storage_location:row.storage_location||"",notes:row.notes||""});if(!result.success)throw new Error(`Inventory row ${index+2}: ${result.error.issues[0].message}`);return result.data;});
  const result=await supabase.rpc("import_inventory_rows",{target_org:identity.organizationId,payload:normalized});if(result.error)throw new Error(result.error.message.includes("duplicate")?"An inventory code in the CSV already exists.":"Inventory import failed; no rows were committed.");
  revalidatePath("/app/inventory");revalidatePath("/app/analytics");redirect(`/app/imports?inventory=${result.data}`);
}

export async function importExperimentsCsv(formData:FormData){
  const {identity}=await context("lab:write");const file=formData.get("file"),projectId=textField(formData,"projectId");if(!(file instanceof File)||!file.name.toLowerCase().endsWith(".csv"))throw new Error("Choose an experiments CSV file.");if(!z.string().uuid().safeParse(projectId).success)throw new Error("Choose the project for this import.");const admin=createAdminClient();const project=await admin.from("projects").select("id").eq("id",projectId).eq("organization_id",identity.organizationId).maybeSingle();if(project.error||!project.data)throw new Error("Project not found in this workspace.");const rows=await csvRows(file);
  const normalized=rows.map((row,index)=>{const result=experimentImportRowSchema.safeParse({...row,priority:row.priority||"medium",tags:row.tags||"",notes:row.notes||""});if(!result.success)throw new Error(`Experiment row ${index+2}: ${result.error.issues[0].message}`);return result.data;});
  const year=new Date().getUTCFullYear();const records=normalized.map(row=>({organization_id:identity.organizationId,code:`EXP-${year}-${crypto.randomUUID().slice(0,8).toUpperCase()}`,title:row.title,project_id:projectId,objective:row.objective,owner_id:identity.userId,experiment_type:row.experiment_type,start_date:row.start_date||null,status:row.start_date?"planned":"draft",priority:row.priority,notes:row.notes,tags:row.tags.split(",").map(tag=>tag.trim()).filter(Boolean).slice(0,20),created_by:identity.userId}));
  const inserted=await admin.from("experiments").insert(records).select("id");if(inserted.error)throw new Error("Experiment import failed; no rows were committed.");await Promise.all([admin.from("activity_log").insert({organization_id:identity.organizationId,actor_id:identity.userId,action:"experiments_csv_imported",record_type:"Experiment import",summary:`${records.length} experiment rows imported`}),event(identity.organizationId,identity.userId,"experiments_csv_imported","Experiment import",undefined,{rows:records.length})]);revalidatePath("/app/experiments");revalidatePath("/app/analytics");redirect(`/app/imports?experiments=${records.length}`);
}

export async function saveNotificationPreferences(formData:FormData){
  const {identity,supabase}=await context("records:read");const input=z.object({email:z.string().email(),leadDays:z.coerce.number().int().min(1).max(90),digestFrequency:z.enum(["daily","weekly","off"])}).parse({email:textField(formData,"email"),leadDays:textField(formData,"leadDays"),digestFrequency:textField(formData,"digestFrequency")});const result=await supabase.from("notification_preferences").upsert({organization_id:identity.organizationId,user_id:identity.userId,email:input.email,overdue_tasks:formData.has("overdueTasks"),low_stock:formData.has("lowStock"),expirations:formData.has("expirations"),calibration:formData.has("calibration"),lead_days:input.leadDays,digest_frequency:input.digestFrequency,updated_at:new Date().toISOString()},{onConflict:"organization_id,user_id"});if(result.error)throw new Error("Alert preferences could not be saved.");await event(identity.organizationId,identity.userId,"alert_preferences_updated","Notification preferences");revalidatePath("/app/settings");redirect("/app/settings?alerts=saved");
}

export async function savePilotMetric(formData:FormData){
  const {identity,supabase}=await context("workspace:export");const input=z.object({id:z.string().uuid().optional().or(z.literal("")),name:z.string().min(3).max(120),unit:z.string().min(1).max(40),baseline:z.coerce.number(),target:z.coerce.number(),currentValue:z.union([z.coerce.number(),z.literal("")]),direction:z.enum(["increase","decrease"]),notes:z.string().max(2000)}).parse({id:textField(formData,"id"),name:textField(formData,"name"),unit:textField(formData,"unit"),baseline:textField(formData,"baseline"),target:textField(formData,"target"),currentValue:textField(formData,"currentValue"),direction:textField(formData,"direction"),notes:textField(formData,"notes")});const payload={organization_id:identity.organizationId,name:input.name,unit:input.unit,baseline:input.baseline,target:input.target,current_value:input.currentValue===""?null:input.currentValue,direction:input.direction,notes:input.notes,updated_at:new Date().toISOString()};const result=input.id?await supabase.from("pilot_metrics").update(payload).eq("id",input.id).eq("organization_id",identity.organizationId):await supabase.from("pilot_metrics").insert({...payload,created_by:identity.userId});if(result.error)throw new Error("Pilot metric could not be saved.");await event(identity.organizationId,identity.userId,"pilot_metric_saved","Pilot metric",input.id||undefined);revalidatePath("/app/analytics");redirect("/app/analytics?metric=saved");
}

export async function applyWorkspaceTemplate(formData:FormData){
  const {identity}=await context("lab:write");const key=textField(formData,"templateKey");const template=workspaceTemplates.find(item=>item.key===key);if(!template)throw new Error("Workspace template not found.");const admin=createAdminClient();const existing=await admin.from("workspace_template_runs").select("id").eq("organization_id",identity.organizationId).eq("template_key",template.key).maybeSingle();if(existing.data)throw new Error("This template has already been applied to the workspace.");const suffix=crypto.randomUUID().slice(0,4).toUpperCase();
  const project=await admin.from("projects").insert({organization_id:identity.organizationId,code:`${template.project.codePrefix}-${suffix}`,name:template.project.name,product:template.project.product,description:template.project.description,owner_id:identity.userId,created_by:identity.userId,status:"planning",priority:"high"}).select("id").single();if(project.error)throw new Error("The starter project could not be created.");
  const protocol=await admin.from("protocols").insert({organization_id:identity.organizationId,code:`${template.protocol.codePrefix}-${suffix}`,name:template.protocol.name,description:template.protocol.description,owner_id:identity.userId,status:"draft",created_by:identity.userId}).select("id").single();if(protocol.error){await admin.from("projects").delete().eq("id",project.data.id);throw new Error("The starter protocol could not be created.");}
  const version=await admin.from("protocol_versions").insert({organization_id:identity.organizationId,protocol_id:protocol.data.id,version:1,title:template.protocol.name,steps:template.protocol.steps,materials:"Define during pilot setup.",equipment:"Define during pilot setup.",notes:"Created from a LabOps onboarding template.",status:"draft",authored_by:identity.userId});const tasks=await admin.from("lab_tasks").insert(template.tasks.map((title,index)=>({organization_id:identity.organizationId,title,description:"Starter task created from the selected onboarding workflow.",assigned_to:identity.userId,project_id:project.data.id,priority:index===0?"high":"medium",status:"to_do",created_by:identity.userId})));if(version.error||tasks.error){await admin.from("lab_tasks").delete().eq("organization_id",identity.organizationId).eq("project_id",project.data.id);await Promise.all([admin.from("protocols").delete().eq("id",protocol.data.id),admin.from("projects").delete().eq("id",project.data.id)]);throw new Error("The template could not be applied completely; created records were rolled back.");}
  const run=await admin.from("workspace_template_runs").insert({organization_id:identity.organizationId,template_key:template.key,applied_by:identity.userId,created_record_count:5});if(run.error){await admin.from("lab_tasks").delete().eq("organization_id",identity.organizationId).eq("project_id",project.data.id);await Promise.all([admin.from("protocols").delete().eq("id",protocol.data.id),admin.from("projects").delete().eq("id",project.data.id)]);throw new Error("The template could not be applied completely; created records were rolled back.");}await Promise.all([admin.from("activity_log").insert({organization_id:identity.organizationId,actor_id:identity.userId,action:"workspace_template_applied",record_type:"Workspace template",summary:`${template.name} starter workflow applied`}),event(identity.organizationId,identity.userId,"workspace_template_applied","Workspace template",undefined,{template:template.key})]);revalidatePath("/app");revalidatePath("/app/get-started");redirect(`/app/get-started?applied=${template.key}`);
}
