"use server";

import { createHash } from "node:crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireWorkspaceIdentity } from "@/lib/auth";
import { can } from "@/lib/security/permissions";
import { createAdminClient } from "@/lib/supabase/admin";
import { getExperimentOperationalContext } from "@/lib/data/traceability";

const text=(data:FormData,name:string)=>String(data.get(name)??"").trim();
async function writeContext(){const identity=await requireWorkspaceIdentity();if(identity.demo)throw new Error("Demo records are read-only.");if(!can(identity.role,"lab:write"))throw new Error("You do not have permission to change traceability records.");return {identity,admin:createAdminClient()};}
async function activity(organizationId:string,userId:string,action:string,recordType:string,recordId:string,summary:string){const admin=createAdminClient();await Promise.all([admin.from("activity_log").insert({organization_id:organizationId,actor_id:userId,action,record_type:recordType,record_id:recordId,summary}),admin.from("product_events").insert({organization_id:organizationId,actor_id:userId,event_name:action,entity_type:recordType,entity_id:recordId})]);}
async function exists(table:"projects"|"device_builds"|"components"|"lots"|"experiments"|"equipment",id:string,organizationId:string){const result=await createAdminClient().from(table).select("id").eq("id",id).eq("organization_id",organizationId).maybeSingle();if(result.error||!result.data)throw new Error("A referenced record was not found in this workspace.");}

export async function createDeviceBuild(formData:FormData){
  const {identity,admin}=await writeContext();const input=z.object({projectId:z.string().uuid().optional().or(z.literal("")),code:z.string().min(2).max(50),name:z.string().min(3).max(180),revision:z.string().min(1).max(30),serialNumber:z.string().max(120),firmwareVersion:z.string().max(120),configuration:z.string().max(4000),status:z.enum(["planned","in_build","available","consumed","quarantined","retired"]),builtAt:z.string().date().optional().or(z.literal("")),notes:z.string().max(4000)}).parse({projectId:text(formData,"projectId"),code:text(formData,"code"),name:text(formData,"name"),revision:text(formData,"revision"),serialNumber:text(formData,"serialNumber"),firmwareVersion:text(formData,"firmwareVersion"),configuration:text(formData,"configuration"),status:text(formData,"status"),builtAt:text(formData,"builtAt"),notes:text(formData,"notes")});if(input.projectId)await exists("projects",input.projectId,identity.organizationId);
  const result=await admin.from("device_builds").insert({organization_id:identity.organizationId,project_id:input.projectId||null,code:input.code,name:input.name,revision:input.revision,serial_number:input.serialNumber,firmware_version:input.firmwareVersion,configuration:input.configuration,status:input.status,built_at:input.builtAt||null,notes:input.notes,created_by:identity.userId}).select("id").single();if(result.error)throw new Error("Device build could not be created. Verify that its identifier is unique.");await activity(identity.organizationId,identity.userId,"device_build_created","Device build",result.data.id,`${input.code} revision ${input.revision} created`);revalidatePath("/app/builds");redirect(`/app/builds/${result.data.id}`);
}

export async function addBuildMaterial(formData:FormData){
  const {identity,admin}=await writeContext();const input=z.object({buildId:z.string().uuid(),componentId:z.string().uuid(),lotId:z.string().uuid(),quantity:z.coerce.number().positive(),referenceDesignator:z.string().max(120),notes:z.string().max(2000)}).parse({buildId:text(formData,"buildId"),componentId:text(formData,"componentId"),lotId:text(formData,"lotId"),quantity:text(formData,"quantity"),referenceDesignator:text(formData,"referenceDesignator"),notes:text(formData,"notes")});await Promise.all([exists("device_builds",input.buildId,identity.organizationId),exists("components",input.componentId,identity.organizationId),exists("lots",input.lotId,identity.organizationId)]);const lot=await admin.from("lots").select("component_id,internal_lot").eq("id",input.lotId).eq("organization_id",identity.organizationId).maybeSingle();if(lot.error||!lot.data||lot.data.component_id!==input.componentId)throw new Error("The selected supplier lot does not belong to the selected component.");const result=await admin.from("device_build_items").insert({organization_id:identity.organizationId,build_id:input.buildId,component_id:input.componentId,lot_id:input.lotId,quantity:input.quantity,reference_designator:input.referenceDesignator,notes:input.notes,added_by:identity.userId});if(result.error)throw new Error("This material-lot link could not be added; it may already exist.");await activity(identity.organizationId,identity.userId,"device_build_material_added","Device build",input.buildId,`${lot.data.internal_lot} added to build genealogy`);revalidatePath(`/app/builds/${input.buildId}`);revalidatePath("/app/experiments");
}

export async function linkExperimentBuild(formData:FormData){const {identity,admin}=await writeContext();const input=z.object({experimentId:z.string().uuid(),buildId:z.string().uuid()}).parse({experimentId:text(formData,"experimentId"),buildId:text(formData,"buildId")});await Promise.all([exists("experiments",input.experimentId,identity.organizationId),exists("device_builds",input.buildId,identity.organizationId)]);const result=await admin.from("experiment_builds").upsert({organization_id:identity.organizationId,experiment_id:input.experimentId,build_id:input.buildId,linked_by:identity.userId},{onConflict:"experiment_id,build_id",ignoreDuplicates:true});if(result.error)throw new Error("The build could not be linked.");await activity(identity.organizationId,identity.userId,"experiment_build_linked","Experiment",input.experimentId,"Device build linked to experiment genealogy");revalidatePath(`/app/experiments/${input.experimentId}`);}

export async function linkExperimentEquipment(formData:FormData){const {identity,admin}=await writeContext();const input=z.object({experimentId:z.string().uuid(),equipmentId:z.string().uuid()}).parse({experimentId:text(formData,"experimentId"),equipmentId:text(formData,"equipmentId")});await Promise.all([exists("experiments",input.experimentId,identity.organizationId),exists("equipment",input.equipmentId,identity.organizationId)]);const result=await admin.from("experiment_equipment").upsert({organization_id:identity.organizationId,experiment_id:input.experimentId,equipment_id:input.equipmentId,linked_by:identity.userId},{onConflict:"experiment_id,equipment_id",ignoreDuplicates:true});if(result.error)throw new Error("The equipment could not be linked.");await activity(identity.organizationId,identity.userId,"experiment_equipment_linked","Experiment",input.experimentId,"Equipment linked for readiness evaluation");revalidatePath(`/app/experiments/${input.experimentId}`);}

export async function evaluateExperimentReadinessAction(formData:FormData){const {identity,admin}=await writeContext();const experimentId=z.string().uuid().parse(text(formData,"experimentId"));const context=await getExperimentOperationalContext(identity,experimentId);if(!context)throw new Error("Experiment not found.");const result=await admin.from("readiness_snapshots").insert({organization_id:identity.organizationId,experiment_id:experimentId,status:context.readiness.status,checks:context.readiness.checks,evaluated_by:identity.userId});if(result.error)throw new Error("Readiness evaluation could not be recorded.");await activity(identity.organizationId,identity.userId,"experiment_readiness_evaluated","Experiment",experimentId,`${context.experiment.code} evaluated as ${context.readiness.status.replace("_"," ")}`);revalidatePath(`/app/experiments/${experimentId}`);}

export async function generateEvidencePacket(formData:FormData){const {identity,admin}=await writeContext();const experimentId=z.string().uuid().parse(text(formData,"experimentId"));const context=await getExperimentOperationalContext(identity,experimentId);if(!context)throw new Error("Experiment not found.");const latest=await admin.from("evidence_packets").select("version").eq("organization_id",identity.organizationId).eq("experiment_id",experimentId).order("version",{ascending:false}).limit(1).maybeSingle();if(latest.error)throw new Error("Evidence history could not be loaded.");const version=(latest.data?.version??0)+1,{packets:_,...captured}=context;void _;const snapshot={organization:identity.organizationName,generatedAt:new Date().toISOString(),generatedBy:identity.fullName,...captured};const serialized=JSON.stringify(snapshot),checksum=createHash("sha256").update(serialized).digest("hex"),packetNumber=`EVP-${context.experiment.code.replace(/^EXP-/,"")}-${String(version).padStart(2,"0")}`;const result=await admin.from("evidence_packets").insert({organization_id:identity.organizationId,experiment_id:experimentId,packet_number:packetNumber,version,readiness_status:context.readiness.status,snapshot,checksum_sha256:checksum,created_by:identity.userId}).select("id").single();if(result.error)throw new Error("Evidence packet could not be frozen.");await activity(identity.organizationId,identity.userId,"evidence_packet_created","Evidence packet",result.data.id,`${packetNumber} frozen from ${context.experiment.code}`);revalidatePath(`/app/experiments/${experimentId}`);redirect(`/app/evidence/${result.data.id}`);}
