import { AlertTriangle, Plus } from "lucide-react";
import { adjustInventory, createInventoryItem } from "../lab-actions";
import { requireWorkspaceIdentity } from "@/lib/auth";
import { listExperiments, listInventory, listInventoryTransactions } from "@/lib/data/lab-operations";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { DataTable, Td } from "@/components/ui/data-table";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { RegistryToolbar } from "@/components/ui/registry-toolbar";
import { SubmitButton } from "@/components/ui/submit-button";
import { formatDate } from "@/lib/utils";
import { isExpiringWithinDays } from "@/lib/lab-workflows";

export default async function InventoryPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;new?:string;adjust?:string}>}){const identity=await requireWorkspaceIdentity();const params=await searchParams;const [items,transactions,experiments]=await Promise.all([listInventory(identity,params),listInventoryTransactions(identity),listExperiments(identity)]);const selected=items.find(i=>i.id===params.adjust);return <><PageHeader eyebrow="Controlled stock" title="Inventory & reagents" description="Monitor stock thresholds and expiry, with every quantity change stored as an immutable transaction." actions={!identity.demo?<ButtonLink href="/app/inventory?new=1"><Plus size={16}/>New item</ButtonLink>:undefined}/>
{params.new==="1"&&!identity.demo?<Card><CardHeader title="Add inventory item" description="The initial quantity is recorded as a receipt transaction."/><CardContent><form action={createInventoryItem} className="form-grid">{[["code","Item code"],["name","Name"],["manufacturer","Manufacturer"],["catalogNumber","Catalog number"],["lotNumber","Lot number"],["unit","Unit"],["storageLocation","Storage location"]].map(([name,label])=><div className="form-field" key={name}><label htmlFor={name}>{label}</label><input id={name} name={name} required={["code","name","unit"].includes(name)}/></div>)}<div className="form-field"><label htmlFor="type">Type</label><select id="type" name="type"><option value="reagent">Reagent</option><option value="chemical">Chemical</option><option value="consumable">Consumable</option><option value="kit">Kit</option><option value="disposable">Disposable</option></select></div><div className="form-field"><label htmlFor="quantity">Initial quantity</label><input id="quantity" name="quantity" type="number" min="0" step="any" defaultValue="0" required/></div><div className="form-field"><label htmlFor="minimumStock">Minimum stock</label><input id="minimumStock" name="minimumStock" type="number" min="0" step="any" defaultValue="0" required/></div><div className="form-field"><label htmlFor="receivedDate">Received</label><input id="receivedDate" name="receivedDate" type="date"/></div><div className="form-field"><label htmlFor="expirationDate">Expires</label><input id="expirationDate" name="expirationDate" type="date"/></div><div className="form-field form-field-wide"><label htmlFor="notes">Notes</label><textarea id="notes" name="notes" rows={3}/></div><div className="form-field-wide flex gap-3"><SubmitButton idle="Add item" pending="Adding…"/><ButtonLink href="/app/inventory" variant="secondary">Cancel</ButtonLink></div></form></CardContent></Card>:null}
{selected&&!identity.demo?<Card><CardHeader title={`Adjust ${selected.code}`} description="Use, disposal, and transfer are stored as negative movements. Balances cannot go below zero."/><CardContent><form action={adjustInventory} className="form-grid"><input type="hidden" name="itemId" value={selected.id}/><div className="form-field"><label htmlFor="type">Transaction type</label><select id="type" name="type"><option value="receipt">Receipt</option><option value="use">Use</option><option value="adjustment">Adjustment</option><option value="disposal">Disposal</option><option value="transfer">Transfer out</option></select></div><div className="form-field"><label htmlFor="amount">Amount</label><input id="amount" name="amount" type="number" step="any" required/></div><div className="form-field"><label htmlFor="experimentId">Related experiment</label><select id="experimentId" name="experimentId"><option value="">None</option>{experiments.map(e=><option key={e.id} value={e.id}>{e.code}</option>)}</select></div><div className="form-field"><label htmlFor="reason">Reason</label><input id="reason" name="reason" minLength={3} required/></div><div className="form-field-wide flex gap-3"><SubmitButton idle="Record transaction" pending="Recording…"/><ButtonLink href="/app/inventory" variant="secondary">Cancel</ButtonLink></div></form></CardContent></Card>:null}
<Card><RegistryToolbar q={params.q} status={params.status} statuses={[{value:"low",label:"Low stock"}]}/>{items.length?<DataTable caption="Inventory" headers={["Item","Lot / manufacturer","Balance","Location","Expiry","Action"]}>{items.map(i=>{const low=i.quantity<=i.minimumStock,warning=isExpiringWithinDays(i.expirationDate);return <tr key={i.id}><Td><strong className="block text-slate-950">{i.code}</strong>{i.name}</Td><Td>{i.manufacturer||"—"}<span className="block text-xs text-slate-500">Lot {i.lotNumber||"—"}</span></Td><Td><strong>{i.quantity} {i.unit}</strong>{low?<Badge className="ml-2" tone="danger">Low stock</Badge>:null}</Td><Td>{i.storageLocation||"—"}</Td><Td>{i.expirationDate?<span className={warning?"font-semibold text-amber-800":""}>{formatDate(i.expirationDate)}{warning?<AlertTriangle className="ml-1 inline" size={14}/>:null}</span>:"—"}</Td><Td>{!identity.demo?<ButtonLink href={`/app/inventory?adjust=${i.id}`} variant="secondary">Adjust</ButtonLink>:<span className="text-xs text-slate-500">Read only</span>}</Td></tr>})}</DataTable>:<EmptyState title="No inventory items found" description="Clear the filters or create the first stock-controlled item."/>}</Card>
<Card><CardHeader title="Recent inventory transactions" description="This ledger is append-only."/><DataTable caption="Inventory transactions" headers={["When","Item","Type","Change","Balance","Reason","Actor"]}>{transactions.map(t=><tr key={t.id}><Td>{formatDate(t.createdAt)}</Td><Td>{items.find(i=>i.id===t.itemId)?.code??t.itemId}</Td><Td>{t.type}</Td><Td className={t.quantityDelta<0?"text-red-700":"text-emerald-700"}>{t.quantityDelta>0?"+":""}{t.quantityDelta}</Td><Td>{t.resultingQuantity}</Td><Td>{t.reason}</Td><Td>{t.actor}</Td></tr>)}</DataTable></Card></>}
