"use server";

import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {z} from "zod";
import {requireWorkspaceIdentity} from "@/lib/auth";
import {can} from "@/lib/security/permissions";
import {createAdminClient} from "@/lib/supabase/admin";
import {documentSkeleton,qualityDocumentCatalog} from "@/lib/quality-documents/catalog";

const text=(data:FormData,key:string)=>String(data.get(key)??"").trim();
async function context(permission:"lab:write"|"lab:review"){const identity=await requireWorkspaceIdentity();if(identity.demo)throw new Error("Demo records are read-only.");if(!can(identity.role,permission))throw new Error("You do not have permission to perform this action.");return {identity,admin:createAdminClient()};}
async function activity(org:string,user:string,action:string,id:string,summary:string){const admin=createAdminClient();await Promise.all([admin.from("activity_log").insert({organization_id:org,actor_id:user,action,record_type:"Quality document",record_id:id,summary}),admin.from("product_events").insert({organization_id:org,actor_id:user,event_name:action,entity_type:"quality_document",entity_id:id})]);}

export async function createQualityDocumentPlan(formData:FormData){const {identity,admin}=await context("lab:write");const input=z.object({projectId:z.string().uuid(),profileId:z.union([z.string().uuid(),z.literal("")])}).parse({projectId:text(formData,"projectId"),profileId:text(formData,"profileId")});const [project,profile]=await Promise.all([admin.from("projects").select("id,name,product").eq("organization_id",identity.organizationId).eq("id",input.projectId).is("deleted_at",null).maybeSingle(),input.profileId?admin.from("regulatory_profiles").select("id,product_name").eq("organization_id",identity.organizationId).eq("id",input.profileId).maybeSingle():Promise.resolve({data:null,error:null})]);if(project.error||!project.data||profile.error||(input.profileId&&!profile.data))throw new Error("Project or regulatory profile not found.");const product=profile.data?.product_name||project.data.product||project.data.name;
  for(const item of qualityDocumentCatalog){const created=await admin.from("quality_documents").upsert({organization_id:identity.organizationId,project_id:input.projectId,regulatory_profile_id:input.profileId||null,document_key:item.key,title:item.title,lifecycle_phase:item.phase,quality_file:item.qualityFile,regulatory_basis:item.basis,applicability:item.applicability,planned_start_week:item.startWeek,planned_end_week:item.endWeek,owner_id:identity.userId,created_by:identity.userId,updated_at:new Date().toISOString()},{onConflict:"organization_id,project_id,document_key",ignoreDuplicates:true}).select("id,current_revision").maybeSingle();if(created.error)throw new Error("The document plan could not be generated.");if(created.data){const revision=await admin.from("quality_document_revisions").insert({organization_id:identity.organizationId,document_id:created.data.id,revision:1,content:documentSkeleton(item,product),source:"template",created_by:identity.userId});if(revision.error)throw new Error("A document shell could not be created.");}}
  await activity(identity.organizationId,identity.userId,"quality_document_plan_created",input.projectId,`${qualityDocumentCatalog.length} controlled document shells planned`);revalidatePath("/app/documents");redirect(`/app/documents?project=${input.projectId}`);
}

const saveSchema=z.object({documentId:z.string().uuid(),content:z.string().trim().min(10).max(100000),source:z.enum(["user","ai_assisted"]),model:z.string().max(100).optional(),promptVersion:z.string().max(100).optional(),generatedAt:z.string().datetime().optional(),dlpSummary:z.string().max(8000).optional()});
export async function saveQualityDocumentRevision(raw:z.input<typeof saveSchema>){const {identity,admin}=await context("lab:write");const input=saveSchema.parse(raw);const document=await admin.from("quality_documents").select("id,title,status,current_revision").eq("id",input.documentId).eq("organization_id",identity.organizationId).maybeSingle();if(document.error||!document.data)throw new Error("Quality document not found.");if(["in_review","approved","obsolete"].includes(document.data.status))throw new Error("This document is locked. Request changes or create a controlled change before editing.");const next=document.data.current_revision+1;const revision=await admin.from("quality_document_revisions").insert({organization_id:identity.organizationId,document_id:input.documentId,revision:next,content:input.content,source:input.source,ai_metadata:input.source==="ai_assisted"?{model:input.model,prompt_version:input.promptVersion,generated_at:input.generatedAt,human_review_required:true}:{},dlp_summary:input.dlpSummary?JSON.parse(input.dlpSummary):{},created_by:identity.userId});if(revision.error)throw new Error("The new revision could not be saved.");const update=await admin.from("quality_documents").update({current_revision:next,status:"draft",updated_at:new Date().toISOString()}).eq("id",input.documentId).eq("organization_id",identity.organizationId).eq("current_revision",document.data.current_revision);if(update.error)throw new Error("The document revision index could not be updated.");await activity(identity.organizationId,identity.userId,"quality_document_revised",input.documentId,`${document.data.title} revision ${next} saved`);revalidatePath(`/app/documents/${input.documentId}`);return {revision:next};}

export async function submitQualityDocumentForReview(formData:FormData){const {identity,admin}=await context("lab:write");const id=z.string().uuid().parse(text(formData,"documentId"));const document=await admin.from("quality_documents").select("id,title,status,current_revision").eq("id",id).eq("organization_id",identity.organizationId).maybeSingle();if(document.error||!document.data)throw new Error("Quality document not found.");if(!["draft","changes_requested"].includes(document.data.status))throw new Error("Only a draft can be submitted.");const latest=await admin.from("quality_document_revisions").select("id").eq("document_id",id).eq("organization_id",identity.organizationId).eq("revision",document.data.current_revision).maybeSingle();if(latest.error||!latest.data)throw new Error("Current revision not found.");const review=await admin.from("quality_document_reviews").insert({organization_id:identity.organizationId,document_id:id,revision_id:latest.data.id,decision:"submitted",comment:text(formData,"comment"),reviewer_id:identity.userId});const update=await admin.from("quality_documents").update({status:"in_review",updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",identity.organizationId);if(review.error||update.error)throw new Error("The document could not be submitted for review.");await activity(identity.organizationId,identity.userId,"quality_document_submitted",id,`${document.data.title} submitted for review`);revalidatePath(`/app/documents/${id}`);revalidatePath("/app/documents");}

export async function reviewQualityDocument(formData:FormData){const {identity,admin}=await context("lab:review");const input=z.object({documentId:z.string().uuid(),decision:z.enum(["approved","changes_requested"]),comment:z.string().trim().min(10).max(4000)}).parse({documentId:text(formData,"documentId"),decision:text(formData,"decision"),comment:text(formData,"comment")});const document=await admin.from("quality_documents").select("id,title,status,current_revision").eq("id",input.documentId).eq("organization_id",identity.organizationId).maybeSingle();if(document.error||!document.data||document.data.status!=="in_review")throw new Error("This document is not awaiting review.");const revision=await admin.from("quality_document_revisions").select("id,created_by").eq("document_id",input.documentId).eq("organization_id",identity.organizationId).eq("revision",document.data.current_revision).maybeSingle();if(revision.error||!revision.data)throw new Error("Current revision not found.");if(revision.data.created_by===identity.userId)throw new Error("The author of this revision cannot approve their own work.");const review=await admin.from("quality_document_reviews").insert({organization_id:identity.organizationId,document_id:input.documentId,revision_id:revision.data.id,decision:input.decision,comment:input.comment,reviewer_id:identity.userId});const update=await admin.from("quality_documents").update({status:input.decision,updated_at:new Date().toISOString()}).eq("id",input.documentId).eq("organization_id",identity.organizationId);if(review.error||update.error)throw new Error("The review decision could not be recorded.");await activity(identity.organizationId,identity.userId,`quality_document_${input.decision}`,input.documentId,`${document.data.title}: ${input.decision.replace("_"," ")}`);revalidatePath(`/app/documents/${input.documentId}`);revalidatePath("/app/documents");}
