import Link from "next/link";
import {ArrowRight,CalendarRange,FileCheck2,Plus,ShieldCheck} from "lucide-react";
import {requireWorkspaceIdentity} from "@/lib/auth";
import {listProjects} from "@/lib/data/workspace";
import {listRegulatoryProfiles} from "@/lib/data/regulatory";
import {listQualityDocuments} from "@/lib/data/quality-documents";
import {qualityPhases} from "@/lib/quality-documents/catalog";
import {can} from "@/lib/security/permissions";
import {Badge} from "@/components/ui/badge";
import {ButtonLink} from "@/components/ui/button";
import {Card,CardContent,CardHeader} from "@/components/ui/card";
import {EmptyState} from "@/components/ui/empty-state";
import {PageHeader} from "@/components/ui/page-header";
import {SubmitButton} from "@/components/ui/submit-button";
import {createQualityDocumentPlan} from "./actions";

const tones={draft:"neutral",in_review:"warning",changes_requested:"danger",approved:"good",obsolete:"neutral"} as const;
const labels={draft:"Draft",in_review:"In review",changes_requested:"Changes requested",approved:"Approved",obsolete:"Obsolete"};

export default async function QualityDocumentsPage({searchParams}:{searchParams:Promise<{project?:string}>}){const identity=await requireWorkspaceIdentity(),params=await searchParams;const [projects,profiles]=await Promise.all([listProjects(identity),listRegulatoryProfiles(identity)]);const selected=projects.find((item)=>item.id===params.project)??projects[0]??null,documents=selected?await listQualityDocuments(identity,selected.id):[],profile=profiles.find((item)=>item.projectId===selected?.id),mayWrite=!identity.demo&&can(identity.role,"lab:write");
  return <><PageHeader eyebrow="QMSR-aligned design & development workspace" title="Quality Document Studio" description="Plan the medical-device development record, create privacy-first AI rough templates, edit controlled revisions, and route them to independent human review." actions={<ButtonLink href="/app/regulatory" variant="secondary">Open Regulatory Navigator</ButtonLink>}/>
    <Card className="border-teal-200 bg-gradient-to-br from-white to-teal-50"><CardContent className="grid gap-5 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-sm font-semibold text-teal-900"><ShieldCheck size={18}/>Human-controlled AI + data-loss prevention</div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">AI builds rich rough drafts from public template metadata and an optional screened author instruction. The working document, product name, files, and evidence remain inside LabOps. Secrets are blocked, identifiers are redacted, revisions are immutable, and authors cannot approve their own work.</p></div><Badge tone="good" className="self-start">Screened prompt mode</Badge></CardContent></Card>
    {projects.length?<Card><CardContent className="flex flex-wrap items-end gap-3"><form method="get" className="flex min-w-[280px] flex-1 items-end gap-3"><label className="form-field flex-1"><span>Project</span><select name="project" defaultValue={selected?.id}>{projects.map((item)=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><SubmitButton idle="View plan" pending="Loading…" variant="secondary"/></form>{mayWrite&&selected&&!documents.length?<form action={createQualityDocumentPlan}><input type="hidden" name="projectId" value={selected.id}/><input type="hidden" name="profileId" value={profile?.id??""}/><SubmitButton idle="Create document plan" pending="Creating 21 shells…"/></form>:null}</CardContent></Card>:<Card><EmptyState title="Create a project first" description="A quality-document plan is anchored to a LabOps project." action={<ButtonLink href="/app/projects"><Plus size={16}/>Create project</ButtonLink>}/></Card>}
    <Card><CardHeader title="Development lifecycle" description="A planning sequence derived from FDA's current QMSR design-and-development stages. Week ranges are editable planning defaults—not regulatory deadlines." action={<span className="flex items-center gap-2 text-xs text-slate-500"><CalendarRange size={16}/>Week 0 through postmarket</span>}/><CardContent><div className="grid gap-3 xl:grid-cols-5">{qualityPhases.map((phase)=><div key={phase.number} className="rounded-lg border border-slate-200 bg-white p-4"><div className="mb-3 grid size-8 place-items-center rounded-full bg-teal-700 text-sm font-bold text-white">{phase.number}</div><h3 className="font-semibold text-slate-950">{phase.name}</h3><p className="mt-1 text-xs text-slate-500">{phase.documents.length} planned artifacts</p><ul className="mt-3 space-y-2 text-xs leading-5 text-slate-600">{phase.documents.slice(0,3).map((item)=><li key={item.key}>{item.title}</li>)}{phase.documents.length>3?<li className="font-semibold text-teal-800">+ {phase.documents.length-3} more</li>:null}</ul></div>)}</div></CardContent></Card>
    <Card><CardHeader title={selected?`${selected.code} document plan`:"Document plan"} description={`${documents.length} controlled records · core, conditional, and business artifacts are labeled separately.`}/><CardContent className="space-y-3">{documents.map((item)=><Link key={item.id} href={`/app/documents/${item.id}`} className="grid items-center gap-3 rounded-lg border border-slate-200 p-4 transition-colors hover:border-teal-300 sm:grid-cols-[48px_minmax(0,1fr)_130px_110px_24px]"><span className="grid size-9 place-items-center rounded-lg bg-slate-100 text-sm font-bold text-slate-700">P{item.phase}</span><span><strong className="block text-sm text-slate-950">{item.title}</strong><span className="mt-1 block text-xs text-slate-500">{item.qualityFile} · {item.basis} · weeks {item.startWeek}–{item.endWeek??"ongoing"}</span></span><Badge tone={item.applicability==="core"?"info":"neutral"}>{item.applicability}</Badge><Badge tone={tones[item.status]}>{labels[item.status]}</Badge><ArrowRight size={17}/></Link>)}{selected&&!documents.length?<EmptyState title="No plan generated" description="Create the evidence-oriented document plan for this project. Existing LabOps records are not changed."/>:null}</CardContent></Card>
    <Card><CardContent className="flex gap-3 text-sm leading-6 text-slate-600"><FileCheck2 className="mt-0.5 shrink-0 text-teal-700" size={19}/><p><strong className="text-slate-900">Important boundary:</strong> this workspace organizes records and supports review; it does not determine regulatory applicability, certify compliance, or replace your quality system, ISO standard access, regulatory counsel, or FDA interaction.</p></CardContent></Card>
  </>;
}
