"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Camera, Keyboard, ScanLine, X } from "lucide-react";
import { Button } from "@/components/ui/button";

type Detector={detect:(source:ImageBitmapSource)=>Promise<Array<{rawValue:string}>>};
type DetectorConstructor=new(options?:{formats?:string[]})=>Detector;

export function SampleScanner(){const router=useRouter();const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const frameRef=useRef<number|null>(null);const [active,setActive]=useState(false);const [message,setMessage]=useState("Camera scanning is optional; manual entry always works.");
  function lookup(value:string){const code=value.trim();if(code)router.push(`/app/samples/scan?code=${encodeURIComponent(code)}`);}
  function releaseCamera(){if(frameRef.current!==null)cancelAnimationFrame(frameRef.current);frameRef.current=null;streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;}
  function stop(){releaseCamera();setActive(false);setMessage("Camera stopped. Manual entry is still available.");}
  async function start(){const Detector=(window as unknown as {BarcodeDetector?:DetectorConstructor}).BarcodeDetector;if(!Detector||!navigator.mediaDevices?.getUserMedia){setMessage("This browser does not support camera barcode detection. Use manual entry below.");return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});streamRef.current=stream;if(!videoRef.current)throw new Error("Camera preview unavailable");videoRef.current.srcObject=stream;await videoRef.current.play();const detector=new Detector({formats:["qr_code","code_128","code_39","ean_13"]});setActive(true);setMessage("Scanner active. Point the camera at a sample barcode or QR code.");const scan=async()=>{if(videoRef.current&&streamRef.current){const found=await detector.detect(videoRef.current).catch(()=>[]);if(found[0]?.rawValue){releaseCamera();setActive(false);lookup(found[0].rawValue);return;}frameRef.current=requestAnimationFrame(scan);}};frameRef.current=requestAnimationFrame(scan);}catch{releaseCamera();setActive(false);setMessage("Camera access was unavailable. Enter the sample code or barcode manually.");}}
  useEffect(()=>()=>releaseCamera(),[]);
  return <div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><section className="scanner-panel"><div className="scanner-frame"><video ref={videoRef} muted playsInline aria-label="Barcode camera preview" className={active?"":"hidden"}/>{!active?<div><ScanLine size={42} aria-hidden="true"/><strong>Camera ready when you are</strong><span>No image is uploaded or stored.</span></div>:null}<span className="scanner-corners" aria-hidden="true"/></div><p role="status" aria-live="polite" className="text-sm text-slate-600">{message}</p><div className="flex flex-wrap gap-3">{active?<Button type="button" variant="secondary" onClick={stop}><X size={16} aria-hidden="true"/>Stop camera</Button>:<Button type="button" onClick={start}><Camera size={16} aria-hidden="true"/>Start scanner</Button>}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><Keyboard className="text-teal-700" aria-hidden="true"/><h2 className="mt-4 text-lg font-semibold text-slate-950">Manual lookup</h2><p className="mt-2 text-sm leading-6 text-slate-600">Enter the human-readable sample ID or its registered barcode.</p><form className="mt-5 space-y-4" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);lookup(String(data.get("code")??""));}}><div className="form-field"><label htmlFor="scan-code">Sample ID or barcode</label><input id="scan-code" name="code" autoComplete="off" spellCheck={false} placeholder="SMP-2026-00431" required/></div><Button>Find sample</Button></form></section></div>;
}
