import { Check } from "lucide-react";
import type { Project } from "@/lib/types";
import type { RegulatoryProfile } from "@/lib/data/regulatory";
import { ButtonLink } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { SubmitButton } from "@/components/ui/submit-button";
import { saveRegulatoryProfileBasics, saveRegulatoryProfileFunctions, saveRegulatoryProfileRisk, regenerateRegulatoryAssessment } from "@/app/(workspace)/app/regulatory/actions";

const steps=["Product & use","Markets & functions","Risk & predicate","Review"];
const checkboxItems=[
  ["isIVD","In vitro diagnostic (IVD)"],["isSaMD","Software as a Medical Device (SaMD)"],["hasAI","AI/ML enabled"],["isConnected","Connected device"],["isPatientFacing","Patient-facing"],["isDiagnostic","Diagnostic function"],["isTherapeutic","Therapeutic function"],["isMonitoring","Monitoring function"],["drivesClinicalDecisions","Drives clinical decisions"],
] as const;

export function RegulatoryProfileWizard({step,profile,projects}:{step:number;profile:RegulatoryProfile|null;projects:Project[]}){
  return <div className="space-y-5"><nav aria-label="Regulatory profile progress" className="grid gap-2 sm:grid-cols-4">{steps.map((label,index)=>{const number=index+1,active=number===step,complete=number<step;return <div key={label} className={`flex items-center gap-2 rounded-md border px-3 py-2 text-sm ${active?"border-teal-500 bg-teal-50 text-teal-900":complete?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-slate-200 text-slate-500"}`} aria-current={active?"step":undefined}><span className={`grid size-6 place-items-center rounded-full text-xs font-bold ${active?"bg-teal-700 text-white":complete?"bg-emerald-600 text-white":"bg-slate-100"}`}>{complete?<Check size={14}/>:number}</span>{label}</div>;})}</nav>
    {step===1?<Card><CardHeader title="Product and intended use" description="Describe the current product concept. These inputs drive the preliminary assessment and evidence plan."/><CardContent><form action={saveRegulatoryProfileBasics} className="form-grid"><input type="hidden" name="profileId" value={profile?.id??""}/>{profile?<input type="hidden" name="projectId" value={profile.projectId}/>:null}<div className="form-field"><label htmlFor="projectId">LabOps project</label>{profile?<input value={`${profile.projectCode} · ${profile.projectName}`} disabled/>:<select id="projectId" name="projectId" required defaultValue=""><option value="" disabled>Select a project</option>{projects.map((item)=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select>}</div><div className="form-field"><label htmlFor="productName">Product / device name</label><input id="productName" name="productName" required minLength={2} maxLength={180} defaultValue={profile?.productName}/></div><div className="form-field form-field-wide"><label htmlFor="intendedUse">Intended use</label><textarea id="intendedUse" name="intendedUse" required minLength={10} maxLength={6000} rows={5} defaultValue={profile?.intendedUse} placeholder="What does the product do, for whom, and for what medical purpose?"/></div><div className="form-field"><label htmlFor="intendedUser">Intended user</label><input id="intendedUser" name="intendedUser" required defaultValue={profile?.intendedUser}/></div><div className="form-field"><label htmlFor="targetPopulation">Target patient population</label><input id="targetPopulation" name="targetPopulation" required defaultValue={profile?.targetPopulation}/></div><div className="form-field form-field-wide"><label htmlFor="clinicalEnvironment">Clinical environment</label><input id="clinicalEnvironment" name="clinicalEnvironment" required defaultValue={profile?.clinicalEnvironment} placeholder="Clinical laboratory, hospital, home, point of care…"/></div><div className="form-field-wide flex flex-wrap gap-3"><SubmitButton idle="Save and continue" pending="Saving profile…"/><ButtonLink href={profile?`/app/regulatory?profile=${profile.id}`:"/app/regulatory"} variant="secondary">Cancel</ButtonLink></div></form></CardContent></Card>:null}
    {step===2&&profile?<Card><CardHeader title="Markets and product functions" description="Select every statement that applies to the current intended configuration."/><CardContent><form action={saveRegulatoryProfileFunctions} className="form-grid"><input type="hidden" name="profileId" value={profile.id}/><fieldset className="form-field"><legend>Target markets</legend><div className="mt-2 flex gap-3"><label className="flex items-center gap-2"><input type="checkbox" name="markets" value="US" defaultChecked={profile.markets.includes("US")}/>United States</label><label className="flex items-center gap-2"><input type="checkbox" name="markets" value="EU" defaultChecked={profile.markets.includes("EU")}/>European Union</label></div></fieldset><div className="form-field"><label htmlFor="deviceType">Product configuration</label><select id="deviceType" name="deviceType" defaultValue={profile.deviceType}><option value="hardware">Hardware</option><option value="software">Software</option><option value="combination">Hardware + software</option></select></div><fieldset className="form-field form-field-wide"><legend>Functions and characteristics</legend><div className="mt-2 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{checkboxItems.map(([name,label])=><label key={name} className="flex min-h-12 items-center gap-3 rounded-md border border-slate-200 p-3 text-sm font-medium"><input type="checkbox" name={name} defaultChecked={profile[name]}/><span>{label}</span></label>)}</div></fieldset><div className="form-field-wide flex flex-wrap gap-3"><SubmitButton idle="Save and continue" pending="Saving functions…"/><ButtonLink href={`/app/regulatory?profile=${profile.id}&step=1`} variant="secondary">Back</ButtonLink></div></form></CardContent></Card>:null}
    {step===3&&profile?<Card><CardHeader title="Risk and predicate considerations" description="These answers are decision-support inputs, not a legal risk classification or predicate determination."/><CardContent><form action={saveRegulatoryProfileRisk} className="form-grid"><input type="hidden" name="profileId" value={profile.id}/><div className="form-field form-field-wide"><label htmlFor="failureImpact">If the product fails, the most serious reasonably foreseeable effect could…</label><select id="failureImpact" name="failureImpact" defaultValue={profile.failureImpact}><option value="inconvenience">Cause inconvenience only</option><option value="delay_diagnosis">Delay diagnosis</option><option value="incorrect_diagnosis">Result in an incorrect diagnosis</option><option value="deterioration">Cause deterioration</option><option value="serious_injury">Cause serious injury</option><option value="death">Cause death</option></select></div><div className="form-field form-field-wide"><label htmlFor="predicateAvailability">Has a potentially suitable legally marketed predicate been identified?</label><select id="predicateAvailability" name="predicateAvailability" defaultValue={profile.predicateAvailability}><option value="unknown">Unknown / research not completed</option><option value="yes">Yes — candidate identified, not verified by LabOps</option><option value="no">No candidate identified after research</option></select></div><div className="form-field-wide flex flex-wrap gap-3"><SubmitButton idle="Save and review" pending="Saving risk inputs…"/><ButtonLink href={`/app/regulatory?profile=${profile.id}&step=2`} variant="secondary">Back</ButtonLink></div></form></CardContent></Card>:null}
    {step===4&&profile?<Card><CardHeader title="Review and generate" description="LabOps will apply the versioned deterministic US/FDA ruleset and create an auditable assessment snapshot."/><CardContent className="space-y-5"><dl className="detail-list"><div><dt>Product</dt><dd>{profile.productName}</dd></div><div><dt>Project</dt><dd>{profile.projectCode} · {profile.projectName}</dd></div><div><dt>Markets</dt><dd>{profile.markets.join(" + ")}</dd></div><div><dt>Configuration</dt><dd>{profile.deviceType} · {profile.isIVD?"IVD · ":""}{profile.isSaMD?"SaMD · ":""}{profile.hasAI?"AI/ML · ":""}{profile.isConnected?"Connected":""}</dd></div><div><dt>Failure impact</dt><dd>{profile.failureImpact.replaceAll("_"," ")}</dd></div><div><dt>Predicate</dt><dd>{profile.predicateAvailability}</dd></div></dl><form action={regenerateRegulatoryAssessment} className="flex flex-wrap gap-3"><input type="hidden" name="profileId" value={profile.id}/><SubmitButton idle="Generate preliminary assessment" pending="Applying transparent rules…"/><ButtonLink href={`/app/regulatory?profile=${profile.id}&step=3`} variant="secondary">Back</ButtonLink></form></CardContent></Card>:null}
  </div>;
}
