import { Download,Table2 } from "lucide-react";
import type { RegulatoryProfile } from "@/lib/data/regulatory";
import { generateDesignControlMatrix,generateTraceabilityMatrix } from "@/lib/regulatory/design-controls";
import type { RegulatoryRequirement,RequirementStatus } from "@/lib/regulatory/types";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card,CardContent,CardHeader } from "@/components/ui/card";

const statusLabel:Record<RequirementStatus,string>={not_assessed:"Not assessed",missing:"Missing",partial:"Partial",evidence_linked:"Evidence linked",needs_review:"Needs review"};
const statusTone:Record<RequirementStatus,"neutral"|"danger"|"warning"|"good">={not_assessed:"neutral",missing:"danger",partial:"warning",evidence_linked:"good",needs_review:"warning"};

export function QualitySystemMatrices({profile,requirements}:{profile:RegulatoryProfile;requirements:RegulatoryRequirement[]}){
  const designControls=generateDesignControlMatrix(profile,requirements),traceability=generateTraceabilityMatrix(requirements);
  return <Card><CardHeader title="Auto-generated Quality Tables" description="Living design-control and traceability views generated from the product profile and linked LabOps evidence." action={<div className="flex flex-wrap gap-2"><ButtonLink href={`/api/regulatory/profiles/${profile.id}/matrices/design-controls`} variant="secondary"><Download size={16}/>Design controls CSV</ButtonLink><ButtonLink href={`/api/regulatory/profiles/${profile.id}/matrices/traceability`} variant="secondary"><Download size={16}/>RTM CSV</ButtonLink></div>}/><CardContent className="space-y-6">
    <div className="flex items-start gap-3 rounded-md border border-teal-100 bg-teal-50/70 p-4 text-sm leading-6 text-teal-950"><Table2 size={19} className="mt-0.5 shrink-0"/><p>These tables update automatically when the profile, requirements, or evidence links change. “Evidence linked” means a source record is connected; it does not mean the document is approved or regulatorily adequate.</p></div>
    <details open className="rounded-lg border border-slate-200"><summary className="cursor-pointer list-none p-4 font-semibold text-slate-950">Design-Control Deliverables Matrix <span className="ml-2 text-sm font-normal text-slate-500">{designControls.length} applicable artifacts across 7 stages</span></summary><div className="overflow-x-auto border-t border-slate-200"><table className="min-w-[920px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Development stage</th><th className="p-3">Primary quality file</th><th className="p-3">Required document artifact</th><th className="p-3">Readiness</th><th className="p-3">Linked evidence</th></tr></thead><tbody className="divide-y divide-slate-100">{designControls.map((row)=><tr key={row.id} className="align-top"><td className="p-3 font-semibold text-slate-900">{row.stage}</td><td className="p-3 text-slate-600">{row.primaryQualityFile}</td><td className="p-3"><strong className="text-slate-900">{row.artifact}</strong><p className="mt-1 text-xs text-slate-500">Mapped to: {row.requirementCategories.join(", ").replaceAll("_"," ")}</p></td><td className="p-3"><Badge tone={statusTone[row.status]}>{statusLabel[row.status]}</Badge></td><td className="p-3 text-slate-600">{row.evidence.length?row.evidence.map((item)=>item.label).join("; "):"No evidence linked"}</td></tr>)}</tbody></table></div></details>
    <details className="rounded-lg border border-slate-200"><summary className="cursor-pointer list-none p-4 font-semibold text-slate-950">Requirements Traceability Matrix (RTM) <span className="ml-2 text-sm font-normal text-slate-500">{traceability.length} generated rows</span></summary><div className="overflow-x-auto border-t border-slate-200"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">RTM ID</th><th className="p-3">Source requirement</th><th className="p-3">Trace path</th><th className="p-3">Status</th><th className="p-3">Evidence / next action</th></tr></thead><tbody className="divide-y divide-slate-100">{traceability.map((row)=><tr key={row.id} className="align-top"><td className="p-3 font-mono text-xs font-semibold text-teal-800">{row.id}</td><td className="p-3 font-semibold text-slate-900">{row.sourceRequirement}</td><td className="p-3 text-slate-600">{row.designControlTarget}</td><td className="p-3"><Badge tone={statusTone[row.status]}>{statusLabel[row.status]}</Badge></td><td className="p-3 text-slate-600">{row.evidence.length?<><span className="block text-slate-900">{row.evidence.map((item)=>item.label).join("; ")}</span><span className="mt-1 block text-xs">{row.nextAction}</span></>:row.nextAction}</td></tr>)}</tbody></table></div></details>
  </CardContent></Card>;
}
