"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireWorkspaceIdentity } from "@/lib/auth";
import { can } from "@/lib/security/permissions";
import { createAdminClient } from "@/lib/supabase/admin";
import { assessUSProfile } from "@/lib/regulatory/rules";
import { generateRequirements } from "@/lib/regulatory/requirements";
import { deriveRequirementStatus, summarizeCoverage } from "@/lib/regulatory/readiness";
import { regulatoryReferences } from "@/lib/regulatory/references";
import { REGULATORY_DISCLAIMER, type EvidenceType, type RegulatoryProfileInput } from "@/lib/regulatory/types";
import { evidenceLinkSchema, profileBasicsSchema, profileFunctionSchema, profileRiskSchema } from "@/lib/regulatory/validation";
import { getLatestRegulatoryAssessment, getRegulatoryProfile, listRegulatoryEvidenceOptions, listRegulatoryRequirements, type RegulatoryReadinessReportSnapshot } from "@/lib/data/regulatory";

const text=(data:FormData,name:string)=>String(data.get(name)??"").trim();
async function writeContext(){const identity=await requireWorkspaceIdentity();if(identity.demo)throw new Error("Demo records are read-only.");if(!can(identity.role,"lab:write"))throw new Error("You do not have permission to change regulatory records.");return {identity,admin:createAdminClient()};}
async function exists(table:"projects"|"regulatory_profiles"|"regulatory_requirements",id:string,organizationId:string){const result=await createAdminClient().from(table).select("id").eq("id",id).eq("organization_id",organizationId).maybeSingle();if(result.error||!result.data)throw new Error("A referenced record was not found in this workspace.");}
async function activity(organizationId:string,userId:string,action:string,recordType:string,recordId:string,summary:string){const admin=createAdminClient();const [audit,event]=await Promise.all([admin.from("activity_log").insert({organization_id:organizationId,actor_id:userId,action,record_type:recordType,record_id:recordId,summary}),admin.from("product_events").insert({organization_id:organizationId,actor_id:userId,event_name:action,entity_type:recordType,entity_id:recordId})]);if(audit.error||event.error)throw new Error("The change was saved, but its audit record failed. Contact support.");}

export async function saveRegulatoryProfileBasics(formData:FormData){
  const {identity,admin}=await writeContext();const input=profileBasicsSchema.parse({profileId:text(formData,"profileId"),projectId:text(formData,"projectId"),productName:text(formData,"productName"),intendedUse:text(formData,"intendedUse"),intendedUser:text(formData,"intendedUser"),targetPopulation:text(formData,"targetPopulation"),clinicalEnvironment:text(formData,"clinicalEnvironment")});await exists("projects",input.projectId,identity.organizationId);
  let profileId:string;if(input.profileId){profileId=input.profileId;await exists("regulatory_profiles",profileId,identity.organizationId);const result=await admin.from("regulatory_profiles").update({product_name:input.productName,intended_use:input.intendedUse,intended_user:input.intendedUser,target_population:input.targetPopulation,clinical_environment:input.clinicalEnvironment,wizard_step:2,completed_at:null,updated_at:new Date().toISOString()}).eq("id",profileId).eq("organization_id",identity.organizationId);if(result.error)throw new Error("The regulatory profile could not be updated.");await activity(identity.organizationId,identity.userId,"regulatory_profile_modified","Regulatory profile",profileId,`${input.productName} profile basics updated`);}else{const result=await admin.from("regulatory_profiles").upsert({organization_id:identity.organizationId,project_id:input.projectId,product_name:input.productName,intended_use:input.intendedUse,intended_user:input.intendedUser,target_population:input.targetPopulation,clinical_environment:input.clinicalEnvironment,wizard_step:2,created_by:identity.userId,updated_at:new Date().toISOString()},{onConflict:"organization_id,project_id"}).select("id").single();if(result.error)throw new Error("The regulatory profile could not be created. This project may already have a profile.");profileId=result.data.id;await activity(identity.organizationId,identity.userId,"regulatory_profile_created","Regulatory profile",profileId,`${input.productName} regulatory profile created`);}revalidatePath("/app/regulatory");redirect(`/app/regulatory?profile=${profileId}&step=2`);
}

export async function saveRegulatoryProfileFunctions(formData:FormData){const {identity,admin}=await writeContext();const input=profileFunctionSchema.parse({profileId:text(formData,"profileId"),markets:formData.getAll("markets").map(String),deviceType:text(formData,"deviceType"),isIVD:formData.has("isIVD"),isSaMD:formData.has("isSaMD"),hasAI:formData.has("hasAI"),isConnected:formData.has("isConnected"),isPatientFacing:formData.has("isPatientFacing"),isDiagnostic:formData.has("isDiagnostic"),isTherapeutic:formData.has("isTherapeutic"),isMonitoring:formData.has("isMonitoring"),drivesClinicalDecisions:formData.has("drivesClinicalDecisions")});await exists("regulatory_profiles",input.profileId,identity.organizationId);const result=await admin.from("regulatory_profiles").update({markets:input.markets,device_type:input.deviceType,is_ivd:input.isIVD,is_samd:input.isSaMD,has_ai:input.hasAI,is_connected:input.isConnected,is_patient_facing:input.isPatientFacing,is_diagnostic:input.isDiagnostic,is_therapeutic:input.isTherapeutic,is_monitoring:input.isMonitoring,drives_clinical_decisions:input.drivesClinicalDecisions,wizard_step:3,completed_at:null,updated_at:new Date().toISOString()}).eq("id",input.profileId).eq("organization_id",identity.organizationId);if(result.error)throw new Error("The product-function profile could not be saved.");await activity(identity.organizationId,identity.userId,"regulatory_profile_modified","Regulatory profile",input.profileId,"Target markets and product functions updated");revalidatePath("/app/regulatory");redirect(`/app/regulatory?profile=${input.profileId}&step=3`);}

export async function saveRegulatoryProfileRisk(formData:FormData){const {identity,admin}=await writeContext();const input=profileRiskSchema.parse({profileId:text(formData,"profileId"),failureImpact:text(formData,"failureImpact"),predicateAvailability:text(formData,"predicateAvailability")});await exists("regulatory_profiles",input.profileId,identity.organizationId);const result=await admin.from("regulatory_profiles").update({failure_impact:input.failureImpact,predicate_availability:input.predicateAvailability,wizard_step:4,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",input.profileId).eq("organization_id",identity.organizationId);if(result.error)throw new Error("The risk profile could not be saved.");await activity(identity.organizationId,identity.userId,"regulatory_profile_modified","Regulatory profile",input.profileId,"Risk and predicate inputs updated");revalidatePath("/app/regulatory");redirect(`/app/regulatory?profile=${input.profileId}&step=4`);}

function toProfileInput(profile:Awaited<ReturnType<typeof getRegulatoryProfile>>):RegulatoryProfileInput{if(!profile)throw new Error("Regulatory profile not found.");return {productName:profile.productName,intendedUse:profile.intendedUse,intendedUser:profile.intendedUser,targetPopulation:profile.targetPopulation,clinicalEnvironment:profile.clinicalEnvironment,markets:profile.markets,deviceType:profile.deviceType,isIVD:profile.isIVD,isSaMD:profile.isSaMD,hasAI:profile.hasAI,isConnected:profile.isConnected,isPatientFacing:profile.isPatientFacing,isDiagnostic:profile.isDiagnostic,isTherapeutic:profile.isTherapeutic,isMonitoring:profile.isMonitoring,drivesClinicalDecisions:profile.drivesClinicalDecisions,failureImpact:profile.failureImpact,predicateAvailability:profile.predicateAvailability};}

export async function regenerateRegulatoryAssessment(formData:FormData){const {identity,admin}=await writeContext();const profileId=z.string().uuid().parse(text(formData,"profileId"));const profile=await getRegulatoryProfile(identity,profileId);if(!profile)throw new Error("Regulatory profile not found.");const input=toProfileInput(profile),assessment=assessUSProfile(input);const created=await admin.from("regulatory_assessments").insert({organization_id:identity.organizationId,profile_id:profileId,jurisdiction:assessment.jurisdiction,possible_device_status:assessment.possibleDeviceStatus,possible_classification:assessment.possibleClassification,possible_pathway:assessment.possiblePathway,confidence:assessment.confidence,rule_id:assessment.ruleId,rule_version:assessment.ruleVersion,evaluated_inputs:assessment.evaluatedInputs,reasoning:assessment.reasoning,assumptions:assessment.assumptions,confirmations:assessment.confirmations,created_by:identity.userId}).select("id").single();if(created.error)throw new Error("The regulatory assessment could not be recorded.");const definitions=generateRequirements(input);const current=await admin.from("regulatory_requirements").select("category,status").eq("organization_id",identity.organizationId).eq("profile_id",profileId);if(current.error)throw new Error("Existing evidence requirements could not be loaded.");const statuses=new Map((current.data??[]).map((item)=>[item.category,item.status]));const reset=await admin.from("regulatory_requirements").update({status:"not_assessed",updated_at:new Date().toISOString()}).eq("organization_id",identity.organizationId).eq("profile_id",profileId);if(reset.error)throw new Error("Existing requirement applicability could not be updated.");const rows=definitions.map((item)=>({organization_id:identity.organizationId,profile_id:profileId,generated_by_assessment_id:created.data.id,category:item.category,title:item.title,description:item.description,status:statuses.get(item.category)==="not_assessed"?"missing":statuses.get(item.category)??"missing",rationale:item.rationale,jurisdiction:item.jurisdiction,priority:item.priority,minimum_evidence_count:item.minimumEvidenceCount,updated_at:new Date().toISOString()}));const upsert=await admin.from("regulatory_requirements").upsert(rows,{onConflict:"profile_id,category"});if(upsert.error)throw new Error("Evidence requirements could not be generated.");await activity(identity.organizationId,identity.userId,"regulatory_assessment_regenerated","Regulatory profile",profileId,`${assessment.ruleId} ${assessment.ruleVersion} generated ${definitions.length} evidence requirements`);revalidatePath("/app/regulatory");redirect(`/app/regulatory?profile=${profileId}`);}

async function refreshRequirementStatus(identity:{organizationId:string},requirementId:string,projectId:string){const admin=createAdminClient();const [requirement,links,options]=await Promise.all([admin.from("regulatory_requirements").select("minimum_evidence_count").eq("id",requirementId).eq("organization_id",identity.organizationId).maybeSingle(),admin.from("regulatory_evidence_links").select("evidence_type,evidence_id").eq("requirement_id",requirementId).eq("organization_id",identity.organizationId),listRegulatoryEvidenceOptions(identity as Parameters<typeof listRegulatoryEvidenceOptions>[0],projectId)]);if(requirement.error||!requirement.data||links.error)throw new Error("Requirement status could not be recalculated.");const availableKeys=new Set(options.map((item)=>`${item.evidenceType}:${item.evidenceId}`));const status=deriveRequirementStatus((links.data??[]).map((item)=>({available:availableKeys.has(`${item.evidence_type}:${item.evidence_id}`)})),requirement.data.minimum_evidence_count);const update=await admin.from("regulatory_requirements").update({status,updated_at:new Date().toISOString()}).eq("id",requirementId).eq("organization_id",identity.organizationId);if(update.error)throw new Error("Requirement status could not be updated.");}

export async function linkRegulatoryEvidence(formData:FormData){const {identity,admin}=await writeContext();const input=evidenceLinkSchema.parse({requirementId:text(formData,"requirementId"),evidenceKey:text(formData,"evidenceKey"),notes:text(formData,"notes")});await exists("regulatory_requirements",input.requirementId,identity.organizationId);const requirement=await admin.from("regulatory_requirements").select("profile_id,title,regulatory_profiles!inner(project_id)").eq("id",input.requirementId).eq("organization_id",identity.organizationId).maybeSingle();if(requirement.error||!requirement.data)throw new Error("Evidence requirement not found.");const profile=Array.isArray(requirement.data.regulatory_profiles)?requirement.data.regulatory_profiles[0]:requirement.data.regulatory_profiles;const projectId=profile.project_id;const [evidenceType,evidenceId]=input.evidenceKey.split(":") as [EvidenceType,string];const option=(await listRegulatoryEvidenceOptions(identity,projectId)).find((item)=>item.evidenceType===evidenceType&&item.evidenceId===evidenceId);if(!option)throw new Error("The selected evidence is unavailable or outside this project/workspace.");const result=await admin.from("regulatory_evidence_links").upsert({organization_id:identity.organizationId,requirement_id:input.requirementId,evidence_type:evidenceType,evidence_id:evidenceId,evidence_label:option.label,evidence_href:option.href,notes:input.notes,linked_by:identity.userId},{onConflict:"requirement_id,evidence_type,evidence_id",ignoreDuplicates:true});if(result.error)throw new Error("The evidence could not be linked.");await refreshRequirementStatus(identity,input.requirementId,projectId);await activity(identity.organizationId,identity.userId,"regulatory_evidence_linked","Regulatory requirement",input.requirementId,`${option.label} linked to ${requirement.data.title}`);revalidatePath("/app/regulatory");}

export async function removeRegulatoryEvidence(formData:FormData){const {identity,admin}=await writeContext();const linkId=z.string().uuid().parse(text(formData,"linkId"));const link=await admin.from("regulatory_evidence_links").select("id,requirement_id,evidence_label,regulatory_requirements!inner(profile_id,regulatory_profiles!inner(project_id))").eq("id",linkId).eq("organization_id",identity.organizationId).maybeSingle();if(link.error||!link.data)throw new Error("Evidence link not found.");const requirement=Array.isArray(link.data.regulatory_requirements)?link.data.regulatory_requirements[0]:link.data.regulatory_requirements;const profile=Array.isArray(requirement.regulatory_profiles)?requirement.regulatory_profiles[0]:requirement.regulatory_profiles;const result=await admin.from("regulatory_evidence_links").delete().eq("id",linkId).eq("organization_id",identity.organizationId);if(result.error)throw new Error("The evidence link could not be removed.");await refreshRequirementStatus(identity,link.data.requirement_id,profile.project_id);await activity(identity.organizationId,identity.userId,"regulatory_evidence_removed","Regulatory requirement",link.data.requirement_id,`${link.data.evidence_label} removed`);revalidatePath("/app/regulatory");}

export async function generateRegulatoryReadinessReport(formData:FormData){const {identity,admin}=await writeContext();const profileId=z.string().uuid().parse(text(formData,"profileId"));const profile=await getRegulatoryProfile(identity,profileId);if(!profile)throw new Error("Regulatory profile not found.");const [assessment,requirements,latest]=await Promise.all([getLatestRegulatoryAssessment(identity,profileId),listRegulatoryRequirements(identity,profileId,profile.projectId),admin.from("regulatory_readiness_reports").select("version").eq("organization_id",identity.organizationId).eq("profile_id",profileId).order("version",{ascending:false}).limit(1).maybeSingle()]);if(!assessment)throw new Error("Generate an assessment before creating a readiness report.");if(latest.error)throw new Error("Readiness report history could not be loaded.");const version=(latest.data?.version??0)+1,coverage=summarizeCoverage(requirements),nextActions=requirements.filter((item)=>item.status!=="evidence_linked"&&item.status!=="not_assessed").sort((a,b)=>({critical:0,high:1,medium:2,low:3}[a.priority]-({critical:0,high:1,medium:2,low:3}[b.priority]))).slice(0,8).map((item)=>`${item.status==="missing"?"Create and link":"Review and strengthen"} evidence for ${item.title}.`);const snapshot:RegulatoryReadinessReportSnapshot={title:"Regulatory Readiness Report",organization:identity.organizationName,generatedAt:new Date().toISOString(),generatedBy:identity.fullName,profile,assessment,requirements,coverage,nextActions,references:regulatoryReferences,disclaimer:REGULATORY_DISCLAIMER};const reportNumber=`RRR-${new Date().getUTCFullYear()}-${profile.id.slice(0,8).toUpperCase()}`;const result=await admin.from("regulatory_readiness_reports").insert({organization_id:identity.organizationId,profile_id:profileId,assessment_id:assessment.id,report_number:reportNumber,version,snapshot,created_by:identity.userId}).select("id").single();if(result.error)throw new Error("The readiness report could not be generated.");await activity(identity.organizationId,identity.userId,"regulatory_report_generated","Regulatory readiness report",result.data.id,`${reportNumber} version ${version} generated`);revalidatePath("/app/regulatory");redirect(`/app/regulatory/reports/${result.data.id}`);}
