import { ArrowRight, Building2, ClipboardCheck, PackageSearch } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";
import { marketingMetadata } from "@/lib/seo";

export const metadata = marketingMetadata({
  title: "Supplier & Component Traceability",
  description: "Connect supplier qualification, component records, received lots, incoming inspections, documents, and disposition decisions.",
  path: "/features/traceability",
});
export default function TraceabilityFeaturePage(){return <div><section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-5xl px-5 py-20"><p className="text-sm font-semibold uppercase text-teal-800">Supplier & traceability portal</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold text-slate-950">Follow materials from supplier qualification to incoming inspection.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">Keep supplier status, documents, component mappings, lot identifiers, shipments, inspections, and issues in one connected operational record.</p><ButtonLink href="/request-demo" className="mt-8">Evaluate your traceability flow</ButtonLink></div></section><section className="mx-auto max-w-6xl px-5 py-16"><div className="grid items-stretch gap-4 lg:grid-cols-[1fr_auto_1fr_auto_1fr]">{[[Building2,"Qualify suppliers","Record risk, review status, required documents, and ownership."],[PackageSearch,"Receive lots","Link supplier lot, internal lot, part revision, quantity, and shipment."],[ClipboardCheck,"Inspect and disposition","Record sample size, defects, outcome, quarantine, and follow-up issues."]].map(([Icon,title,body],index)=><div key={String(title)} className="contents"><article className="rounded-lg border border-slate-200 bg-white p-6"><Icon className="text-teal-700"/><h2 className="mt-5 text-lg font-semibold">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{String(body)}</p></article>{index<2&&<ArrowRight className="m-auto hidden text-slate-400 lg:block"/>}</div>)}</div></section></div>}
