import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { getWorkspaceIdentity } from "@/lib/auth";
import { getReport, listProjects } from "@/lib/data/workspace";
import { enforceRateLimit } from "@/lib/security/rate-limit";
import { createAdminClient } from "@/lib/supabase/admin";

function wrap(text: string, max = 88) { const words = text.split(/\s+/); const lines: string[] = []; let line = ""; for (const word of words) { if (`${line} ${word}`.trim().length > max) { lines.push(line); line = word; } else line = `${line} ${word}`.trim(); } if (line) lines.push(line); return lines; }

export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) {
  const identity = await getWorkspaceIdentity(); if (!identity) return NextResponse.json({ error: "Authentication required" }, { status: 401 });
  if (!identity.demo) { const rateLimit = await enforceRateLimit(`${identity.organizationId}:${identity.userId}`, "pdf_export", 30, 3600); if (!rateLimit.allowed) return NextResponse.json({ error: "PDF export limit reached" }, { status: 429 }); }
  const { id } = await params; const admin = createAdminClient();
  if (!identity.demo) { const snapshot = await admin.from("reports").select("pdf_snapshot_path,status").eq("id", id).eq("organization_id", identity.organizationId).maybeSingle(); if (snapshot.data?.status === "approved" && snapshot.data.pdf_snapshot_path) { const signed = await admin.storage.from("labops-files").createSignedUrl(snapshot.data.pdf_snapshot_path, 60, { download: true }); if (signed.data) return NextResponse.redirect(signed.data.signedUrl); } }
  const [report, projects] = await Promise.all([getReport(identity, id), listProjects(identity)]); if (!report) return NextResponse.json({ error: "Report not found" }, { status: 404 }); const project = projects.find((item) => item.id === report.projectId);
  const pdf = await PDFDocument.create(); const regular = await pdf.embedFont(StandardFonts.Helvetica); const bold = await pdf.embedFont(StandardFonts.HelveticaBold); const teal = rgb(0.04, 0.38, 0.36); let page = pdf.addPage([612, 792]); let y = 742;
  const draw = (text: string, options: { size?: number; font?: typeof regular; color?: ReturnType<typeof rgb>; gap?: number } = {}) => { const size = options.size ?? 10; for (const line of wrap(text, size > 14 ? 62 : 92)) { if (y < 60) { page = pdf.addPage([612, 792]); y = 742; } page.drawText(line, { x: 54, y, size, font: options.font ?? regular, color: options.color ?? rgb(0.12, 0.16, 0.22) }); y -= size + 5; } y -= options.gap ?? 4; };
  draw("MICROCD LABOPS BETA", { size: 10, font: bold, color: teal, gap: 10 }); draw(report.title, { size: 20, font: bold, gap: 8 }); draw(`${report.number} | Revision ${report.revision} | ${report.status}`, { size: 10, color: rgb(0.35, 0.4, 0.48), gap: 12 }); draw(`Project: ${project?.code ?? "—"} — ${project?.name ?? "Unknown"}`); draw(`Author: ${report.author}    Reviewer: ${report.reviewer}`); draw(`Classification: ${report.confidentiality}`, { gap: 16 }); if (identity.demo) draw("FICTIONAL DEMONSTRATION RECORD — NOT FOR PRODUCT, CLINICAL, OR REGULATORY USE", { size: 9, font: bold, color: rgb(0.72, 0.2, 0.14), gap: 18 });
  for (const section of report.sections) { draw(section.title, { size: 13, font: bold, color: teal, gap: 4 }); draw(section.content, { gap: 12 }); if (section.source === "ai-assisted") draw("Source note: AI-assisted suggestion accepted by a user; technical review remains required.", { size: 8, color: rgb(0.35, 0.4, 0.48), gap: 10 }); }
  draw("Acceptance criteria", { size: 13, font: bold, color: teal, gap: 5 }); for (const item of report.criteria) draw(`${item.outcome.toUpperCase()}  ${item.measurement}: ${item.result ?? "—"} ${item.unit} | criterion ${item.operator} ${item.minimum ?? item.maximum ?? item.target ?? "—"} ${item.unit}`, { size: 9, gap: 3 }); y -= 15; draw("Review statement", { size: 13, font: bold, color: teal, gap: 4 }); draw("This export records the revision and review state shown above. It is not represented as a regulated electronic signature. Verify the source record before relying on this document.", { size: 9 });
  const bytes = await pdf.save();
  if (!identity.demo) { const action = report.status === "Approved" ? "approved_pdf_snapshot_created" : "report_exported"; if (report.status === "Approved") { const path = `${identity.organizationId}/report/${report.id}/approved-${report.revision}.pdf`; const uploaded = await admin.storage.from("labops-files").upload(path, bytes, { contentType: "application/pdf", upsert: false }); if (!uploaded.error) await admin.from("reports").update({ pdf_snapshot_path: path, locked_at: new Date().toISOString() }).eq("id", report.id).eq("organization_id", identity.organizationId).eq("status", "approved"); } await admin.from("activity_log").insert({ organization_id: identity.organizationId, actor_id: identity.userId, action, record_type: "Report", record_id: report.id, summary: `PDF generated for ${report.number} revision ${report.revision}` }); }
  return new NextResponse(Buffer.from(bytes), { headers: { "Content-Type": "application/pdf", "Content-Disposition": `inline; filename="${report.number}-Rev-${report.revision}.pdf"`, "Cache-Control": "private, no-store" } });
}
