import { marketingMetadata } from "@/lib/seo";

export const metadata = marketingMetadata({
  title: "Security & Product Boundaries",
  description: "Review MicroCD LabOps tenant isolation, private file handling, role controls, AI boundaries, and current product limitations.",
  path: "/security",
});

export default function SecurityPage(){return <article className="prose-legal mx-auto max-w-4xl px-5 py-16"><h1 className="text-4xl font-semibold text-slate-950">Security and product boundaries</h1><p>MicroCD LabOps is designed around tenant isolation, least-privilege roles, private file storage, and auditable changes. These are engineering controls, not a certification or guarantee of regulatory suitability.</p><h2>Organization isolation</h2><p>Every tenant-owned database record includes an organization identifier. PostgreSQL row-level security verifies active membership, while server actions enforce role permissions. Cross-organization identifiers return a not-found response rather than exposing record existence.</p><h2>Authentication and files</h2><p>Supabase Auth manages sessions using server-readable secure cookies. Customer files use a private storage bucket and short-lived signed URLs. Service-role, Stripe, email, and AI keys remain server-only.</p><h2>AI and data-loss prevention</h2><p>AI is disabled unless configured by an administrator. Quality-document generation transmits public template metadata and an optional screened author instruction; it does not transmit the working draft, project name, files, or linked evidence. Report drafting requires per-request authorization and applies server-side credential blocking and identifier redaction before transmission. Provider response storage is disabled. Pattern detection cannot guarantee identification of every secret or regulated datum, so users must not enter patient data, credentials, or confidential IP.</p><h2>Controlled document review</h2><p>Quality documents retain immutable revisions, source provenance, status transitions, and review records. Authors cannot approve their own revision. These controls support a customer validation process; they do not constitute electronic-signature or quality-system certification.</p><h2>Not a regulated quality system</h2><p>The launch product is not claimed to satisfy 21 CFR Part 11, ISO 13485, HIPAA, GDPR, FDA, electronic-signature, clinical validation, or any other regulated requirement. Customers must conduct their own risk, privacy, validation, and regulatory assessment.</p><h2>Report a concern</h2><p>Send security concerns to info@microcdlabs.com. Do not include secrets, patient information, or regulated production data in the first message.</p></article>}
