import { ArrowRight, Beaker, BookOpenCheck, CheckCircle2, ClipboardList, FlaskConical, Microscope, PackageSearch, TestTube2, Warehouse } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { demoEquipment, demoExperiments, demoInventory, demoLabTasks, demoProtocols, demoSamples } from "@/lib/data/lab-demo";
import { marketingMetadata } from "@/lib/seo";

export const metadata = marketingMetadata({
  title: "Interactive LabOps Product Tour",
  description: "Explore a no-login, read-only tour of connected experiments, samples, protocols, inventory, equipment, tasks, and audit-ready laboratory workflows.",
  path: "/product-tour",
});

const running = demoExperiments.filter((experiment) => experiment.status === "Running");
const review = demoExperiments.filter((experiment) => experiment.status === "Under review");
const warnings = demoInventory.filter((item) => item.quantity <= item.minimumStock);
const equipmentAttention = demoEquipment.filter((item) => item.status === "Calibration required" || item.status === "Out of service");
const tourMetrics = [
  { label: "Running experiments", value: running.length, icon: FlaskConical },
  { label: "Review queue", value: review.length, icon: ClipboardList },
  { label: "Low-stock warnings", value: warnings.length, icon: Warehouse },
  { label: "Equipment actions", value: equipmentAttention.length, icon: Microscope },
];

export default function ProductTourPage() {
  const flow = [
    { icon: BookOpenCheck, label: demoProtocols[0].code, title: `${demoProtocols[0].name} v${demoProtocols[0].latestVersion}`, detail: "Approved method is frozen to the experiment." },
    { icon: FlaskConical, label: demoExperiments[0].code, title: demoExperiments[0].title, detail: `${demoExperiments[0].owner} · ${demoExperiments[0].status}` },
    { icon: TestTube2, label: demoSamples[1].code, title: demoSamples[1].name, detail: `${demoSamples[1].quantity} ${demoSamples[1].unit} · ${demoSamples[1].storageLocation}` },
    { icon: Microscope, label: demoEquipment[0].code, title: demoEquipment[0].name, detail: `${demoEquipment[0].status} · ${demoEquipment[0].location}` },
  ];

  return <div>
    <section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-16"><div className="flex flex-wrap items-center gap-3"><Badge tone="info">Read-only product tour</Badge><span className="text-sm text-slate-500">Fictional records · no customer data</span></div><div className="mt-6 grid items-end gap-8 lg:grid-cols-[1fr_auto]"><div><h1 className="max-w-4xl text-4xl font-semibold leading-tight text-slate-950 sm:text-5xl">A laboratory workflow you can understand in five minutes.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">Follow one microfluidic development program across experiments, samples, protocols, inventory, equipment, tasks, and evidence. Every record below is fictional but reflects the working product model.</p></div><ButtonLink href="/request-demo" className="group">Discuss your workflow <ArrowRight size={17} className="transition-transform group-hover:translate-x-1"/></ButtonLink></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-10"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{tourMetrics.map(({label,value,icon:Icon})=><div key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><Icon size={19} className="text-teal-700"/><strong className="mt-5 block text-3xl text-slate-950">{value}</strong><span className="mt-1 block text-sm text-slate-500">{label}</span></div>)}</div></section>

    <section className="mx-auto max-w-7xl px-5 py-10"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Connected context</p><h2 className="mt-3 text-3xl font-semibold text-slate-950">From approved method to the physical run.</h2><p className="mt-3 leading-7 text-slate-600">A scientist should not have to reconstruct this chain from filenames, chat messages, and memory.</p></div><div className="mt-8 grid gap-4 lg:grid-cols-4">{flow.map(({icon:Icon,label,title,detail},index)=><article key={label} className="relative rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-lg bg-teal-50 text-teal-800"><Icon size={20}/></span>{index<flow.length-1?<ArrowRight className="hidden text-slate-300 lg:block" size={18}/>:<CheckCircle2 className="text-emerald-600" size={18}/>}</div><p className="mt-5 text-xs font-bold tracking-wide text-teal-700">{label}</p><h3 className="mt-2 font-semibold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{detail}</p></article>)}</div></section>

    <section className="border-y border-slate-200 bg-slate-50/70"><div className="mx-auto grid max-w-7xl gap-5 px-5 py-14 xl:grid-cols-[1.1fr_.9fr]"><Card><CardHeader title="Experiment requiring review" description="Status, ownership, protocol, results, and next action stay together." action={<Badge tone="warning">{demoExperiments[1].status}</Badge>}/><CardContent><p className="text-xs font-bold text-teal-700">{demoExperiments[1].code}</p><h3 className="mt-2 text-xl font-semibold text-slate-950">{demoExperiments[1].title}</h3><p className="mt-3 leading-7 text-slate-600">{demoExperiments[1].objective}</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Owner",demoExperiments[1].owner],["Protocol",demoExperiments[1].protocolLabel??"—"],["Priority",demoExperiments[1].priority]].map(([label,value])=><div key={label} className="rounded-lg bg-slate-50 p-4"><span className="text-xs text-slate-500">{label}</span><strong className="mt-1 block text-sm text-slate-950">{value}</strong></div>)}</div><div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4"><strong className="text-sm text-amber-950">Reviewer attention</strong><p className="mt-1 text-sm leading-6 text-amber-900">{demoExperiments[1].observations}</p></div></CardContent></Card><div className="grid gap-5"><Card><CardHeader title="Resource warning" action={<Badge tone="danger">Low stock</Badge>}/><CardContent><div className="flex gap-3"><Warehouse className="mt-1 text-amber-700" size={20}/><div><strong className="text-slate-950">{demoInventory[0].code} · {demoInventory[0].name}</strong><p className="mt-1 text-sm text-slate-600">{demoInventory[0].quantity} {demoInventory[0].unit} remaining; minimum {demoInventory[0].minimumStock}.</p><p className="mt-2 text-xs text-slate-500">The balance changes only through preserved inventory transactions.</p></div></div></CardContent></Card><Card><CardHeader title="Upcoming operational task" action={<Badge tone="warning">{demoLabTasks[1].priority}</Badge>}/><CardContent><div className="flex gap-3"><ClipboardList className="mt-1 text-teal-700" size={20}/><div><strong className="text-slate-950">{demoLabTasks[1].title}</strong><p className="mt-1 text-sm text-slate-600">{demoLabTasks[1].description}</p><p className="mt-2 text-xs text-slate-500">{demoLabTasks[1].assignee} · linked to {demoLabTasks[1].experimentCode}</p></div></div></CardContent></Card></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Designed for the work between discovery and scale</p><h2 className="mt-3 text-3xl font-semibold text-slate-950">Operational discipline without pretending to be every enterprise system.</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{[{icon:Beaker,title:"Scientific context",body:"Experiments, samples, methods, observations, and conclusions share a coherent record."},{icon:PackageSearch,title:"Resource readiness",body:"Inventory, suppliers, components, lots, inspections, and equipment make blockers visible."},{icon:ClipboardList,title:"Human follow-through",body:"Owners, roles, tasks, reviews, controlled transitions, and activity history keep work moving."}].map(({icon:Icon,title,body})=><article key={title} className="rounded-xl border border-slate-200 bg-white p-6"><Icon size={22} className="text-teal-700"/><h3 className="mt-5 font-semibold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></article>)}</div><div className="mt-10 rounded-xl bg-slate-950 p-7 text-white sm:flex sm:items-center sm:justify-between sm:gap-8"><div><h2 className="text-2xl font-semibold">Would this remove a real bottleneck in your lab?</h2><p className="mt-2 text-slate-300">A pilot starts with one workflow, a baseline, and a measurable success criterion.</p></div><ButtonLink href="/request-demo" variant="secondary" className="mt-5 shrink-0 bg-white text-slate-950 sm:mt-0">Request a pilot discussion</ButtonLink></div></section>
  </div>;
}
