import { Check } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";
import { marketingMetadata } from "@/lib/seo";

export const metadata = marketingMetadata({
  title: "LabOps Plans & Pilot Pricing",
  description: "Review trial and team plan options for MicroCD LabOps engineering documentation and supplier traceability workflows.",
  path: "/pricing",
});
const plans=[{name:"Trial",price:"$0",text:"Evaluate with fictional or non-sensitive data.",features:["One workspace","Core report workflow","Supplier traceability demo","No production SLA"]},{name:"Team",price:"$79",text:"For a small development team building controlled records.",features:["Up to 5 members","Reports and PDF exports","Supplier, component, lot, and inspection records","Email support"]},{name:"Lab",price:"$199",text:"For cross-functional teams needing more members and storage.",features:["Up to 15 members","Expanded storage","Priority support","Workspace export"]}];
export default function PricingPage(){return <section className="mx-auto max-w-7xl px-5 py-20"><div className="mx-auto max-w-3xl text-center"><h1 className="text-5xl font-semibold text-slate-950">Simple plans for early technical teams.</h1><p className="mt-5 text-lg text-slate-600">Illustrative launch pricing; confirm commercial terms before purchase. Taxes may apply.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map((plan)=><article key={plan.name} className={`rounded-lg border bg-white p-7 ${plan.name==="Team"?"border-teal-700 ring-1 ring-teal-700":"border-slate-200"}`}><h2 className="text-xl font-semibold">{plan.name}</h2><p className="mt-4 text-4xl font-semibold">{plan.price}<span className="text-sm font-normal text-slate-500">{plan.price!=="$0"?" / month":""}</span></p><p className="mt-4 min-h-12 text-sm leading-6 text-slate-600">{plan.text}</p><ul className="mt-6 space-y-3">{plan.features.map(feature=><li key={feature} className="flex gap-2 text-sm"><Check size={17} className="text-teal-700"/>{feature}</li>)}</ul><ButtonLink href={plan.name==="Trial"?"/signup":"/request-demo"} variant={plan.name==="Team"?"primary":"secondary"} className="mt-8 w-full">{plan.name==="Trial"?"Start trial":"Contact sales"}</ButtonLink></article>)}</div><p className="mt-8 text-center text-xs leading-5 text-slate-500">LabOps is not represented as a validated QMS, LIMS, ERP, PLM, CAPA, or regulated electronic-signature system.</p></section>}
