import {notFound} from "next/navigation";
import {History,LockKeyhole,ShieldCheck} from "lucide-react";
import {requireWorkspaceIdentity} from "@/lib/auth";
import {appConfig} from "@/lib/config";
import {getQualityDocument} from "@/lib/data/quality-documents";
import {can} from "@/lib/security/permissions";
import {QualityDocumentEditor} from "@/components/documents/quality-document-editor";
import {Badge} from "@/components/ui/badge";
import {Card,CardContent,CardHeader} from "@/components/ui/card";
import {PageHeader} from "@/components/ui/page-header";
import {SubmitButton} from "@/components/ui/submit-button";
import {formatDate} from "@/lib/utils";
import {reviewQualityDocument,submitQualityDocumentForReview} from "../actions";

const tones={draft:"neutral",in_review:"warning",changes_requested:"danger",approved:"good",obsolete:"neutral"} as const;
const labels={draft:"Draft",in_review:"In review",changes_requested:"Changes requested",approved:"Approved",obsolete:"Obsolete"};

export default async function QualityDocumentPage({params}:{params:Promise<{id:string}>}){const identity=await requireWorkspaceIdentity(),{id}=await params,document=await getQualityDocument(identity,id);if(!document)notFound();const mayWrite=!identity.demo&&can(identity.role,"lab:write"),mayReview=!identity.demo&&can(identity.role,"lab:review"),locked=!mayWrite||["in_review","approved","obsolete"].includes(document.status);
  return <><PageHeader breadcrumbs={[{label:"Quality Document Studio",href:`/app/documents?project=${document.projectId}`},{label:document.title}]} eyebrow={`Phase ${document.phase} · ${document.qualityFile}`} title={document.title} description={`${document.basis} · ${document.applicability} applicability · planned weeks ${document.startWeek}–${document.endWeek??"ongoing"}`} actions={<Badge tone={tones[document.status]}>{labels[document.status]}</Badge>}/>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.65fr)]"><Card><CardHeader title={`Revision ${document.currentRevision}`} description={locked?"This revision is read-only in its current workflow state.":"Prompt AI safely, edit the source, inspect the styled document, and save a new immutable revision."} action={locked?<LockKeyhole size={18} className="text-slate-500"/>:undefined}/><CardContent><QualityDocumentEditor documentId={document.id} title={document.title} revision={locked?document.currentRevision:document.currentRevision+1} initialContent={document.latestRevision?.content??""} locked={locked} configured={appConfig.aiConfigured}/></CardContent></Card>
      <div className="space-y-5"><Card><CardHeader title="Controlled workflow" description="Draft → independent review → approval"/><CardContent className="space-y-4">{mayWrite&&["draft","changes_requested"].includes(document.status)?<form action={submitQualityDocumentForReview} className="space-y-3"><input type="hidden" name="documentId" value={document.id}/><label className="form-field"><span>Submission note</span><textarea name="comment" rows={3} maxLength={4000} placeholder="What changed and what should the reviewer focus on?"/></label><SubmitButton idle="Submit current revision" pending="Submitting…" className="w-full"/></form>:null}{mayReview&&document.status==="in_review"?<form action={reviewQualityDocument} className="space-y-3"><input type="hidden" name="documentId" value={document.id}/><label className="form-field"><span>Decision</span><select name="decision" defaultValue="approved"><option value="approved">Approve revision</option><option value="changes_requested">Request changes</option></select></label><label className="form-field"><span>Review rationale</span><textarea name="comment" rows={4} minLength={10} maxLength={4000} required placeholder="Record the evidence reviewed and decision rationale."/></label><SubmitButton idle="Record review decision" pending="Recording…" className="w-full"/></form>:null}{!mayWrite&&!mayReview?<p className="text-sm text-slate-500">Your role has read-only access to this record.</p>:null}{document.status==="approved"?<p className="flex gap-2 rounded-lg bg-emerald-50 p-3 text-sm leading-6 text-emerald-900"><ShieldCheck className="mt-0.5 shrink-0" size={18}/>Approved revision is immutable. A future change should begin a new controlled revision.</p>:null}</CardContent></Card>
        <Card><CardHeader title="Revision provenance" description="Immutable authorship and AI metadata" action={<History size={18} className="text-slate-500"/>}/><CardContent className="space-y-3"><dl className="detail-list"><div><dt>Revision</dt><dd>{document.currentRevision}</dd></div><div><dt>Source</dt><dd>{document.latestRevision?.source.replace("_"," ")??"Unknown"}</dd></div><div><dt>Created by</dt><dd>{document.latestRevision?.createdBy??"Unknown"}</dd></div><div><dt>Created</dt><dd>{document.latestRevision?formatDate(document.latestRevision.createdAt):"—"}</dd></div><div><dt>Owner</dt><dd>{document.owner}</dd></div></dl>{document.reviews.map((review)=><div key={review.id} className="rounded-md border border-slate-200 p-3 text-sm"><div className="flex items-center justify-between gap-2"><strong className="capitalize">{review.decision.replace("_"," ")}</strong><span className="text-xs text-slate-500">{formatDate(review.createdAt)}</span></div><p className="mt-1 text-xs text-slate-500">{review.reviewer}</p>{review.comment?<p className="mt-2 text-sm leading-6 text-slate-600">{review.comment}</p>:null}</div>)}</CardContent></Card></div>
    </div>
  </>;
}
