import { ArrowRight, CheckCircle2, ClipboardCheck, FileBarChart, FileText, PackageCheck, SearchCheck, ShieldCheck } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";
import { marketingMetadata } from "@/lib/seo";

export const metadata = marketingMetadata({
  title: "Engineering Documentation & Traceability",
  description: "Organize engineering reports, test data, supplier qualification, incoming inspection, and component traceability in one practical workspace.",
  path: "/",
});

const capabilities = [
  { icon: FileText, title: "Evidence-linked engineering reports", body: "Build structured test, verification, failure-analysis, inspection, and design-review records without starting from a blank document." },
  { icon: FileBarChart, title: "Test data and acceptance criteria", body: "Preview CSV data, calculate transparent summary statistics, map criteria, and preserve the evidence behind each conclusion." },
  { icon: SearchCheck, title: "Supplier qualification", body: "Track qualification checklists, owners, due dates, documents, review decisions, and requalification dates." },
  { icon: PackageCheck, title: "Component and lot traceability", body: "Connect suppliers, approved components, received lots, inspections, documents, and project records." },
  { icon: ClipboardCheck, title: "Incoming inspection", body: "Document sampling, measurements, defects, disposition, and follow-up actions in a consistent workflow." },
  { icon: ShieldCheck, title: "Controlled revisions", body: "Route reports for review, record comments and decisions, and preserve approved snapshots rather than silently overwriting them." },
];

export default function Home() {
  return <>
    <section className="hero-grid border-b border-slate-200 bg-white"><div className="mx-auto grid min-h-[520px] max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.02fr_.98fr]"><div><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Engineering operations for scientific hardware teams</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold leading-[1.12] text-slate-950 sm:text-[2.75rem]">Engineering records your team can follow.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">Organize test data, engineering reports, supplier qualification, and component traceability in one practical workspace.</p><div className="mt-7 flex flex-wrap gap-3"><ButtonLink href="/signup">Start free trial <ArrowRight size={17} /></ButtonLink><ButtonLink href="/request-demo" variant="secondary">Request a demo</ButtonLink></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-600">{["Structured documentation", "Traceable records", "Controlled revisions"].map((item) => <span key={item} className="flex items-center gap-2"><CheckCircle2 size={16} className="text-teal-700" />{item}</span>)}</div></div><div className="product-preview"><div className="product-preview-inner"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-xs font-semibold text-teal-700">ETR-CDX-001-01 · REV A</p><strong className="mt-1 block text-slate-950">Spin Profile Evaluation</strong></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-900">Ready for review</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Criteria", "3"], ["Evidence files", "7"], ["Open comment", "1"]].map(([label, value]) => <div key={label} className="rounded-md bg-slate-50 p-4"><span className="text-xs text-slate-500">{label}</span><strong className="mt-1 block text-xl text-slate-950">{value}</strong></div>)}</div><div className="mt-5 space-y-3">{["Objective and scope", "Method and conditions", "Results and criteria", "Engineering conclusion"].map((section, index) => <div key={section} className="flex items-center gap-3 rounded-md border border-slate-200 p-3 text-sm text-slate-700"><span className="grid size-7 place-items-center rounded-full bg-teal-50 text-xs font-bold text-teal-800">{index + 1}</span>{section}</div>)}</div></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">One connected workspace</p><h2 className="mt-3 text-3xl font-semibold text-slate-950 sm:text-4xl">Reports and traceability share the same project evidence.</h2><p className="mt-4 leading-7 text-slate-600">Connect a test result to the component revision, supplier lot, incoming inspection, and certificate that produced it.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(({ icon: Icon, title, body }) => <article key={title} className="rounded-lg border border-slate-200 bg-white p-6"><span className="grid size-10 place-items-center rounded-md bg-teal-50 text-teal-800"><Icon size={20} /></span><h3 className="mt-5 font-semibold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></article>)}</div></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Designed for smaller technical teams</p><h2 className="mt-3 text-3xl font-semibold text-slate-950">Operational rigor without claiming regulatory sufficiency.</h2></div><div><p className="leading-7 text-slate-600">MicroCD LabOps supports organized product-development workflows. It is not a validated QMS, LIMS, ERP, PLM, CAPA, electronic-signature, or regulatory-advice system.</p><ButtonLink href="/security" variant="secondary" className="mt-6">Review security boundaries</ButtonLink></div></div></section>
    <section className="bg-teal-800 px-5 py-14 text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6"><div><h2 className="text-2xl font-semibold">Review a fictional demo workspace.</h2><p className="mt-2 text-teal-100">Explore connected report and supplier workflows before configuring production services.</p></div><ButtonLink href="/app?demo=1" variant="secondary">Open demo workspace</ButtonLink></div></section>
  </>;
}
