import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ExternalLink } from "lucide-react";
import { requireWorkspaceIdentity } from "@/lib/auth";
import { getRegulatoryReport } from "@/lib/data/regulatory";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { RegulatoryDisclaimer } from "@/components/regulatory/regulatory-disclaimer";
import { formatDate } from "@/lib/utils";
import type { RequirementStatus } from "@/lib/regulatory/types";

const labels:Record<RequirementStatus,string>={not_assessed:"Not Assessed",missing:"Missing",partial:"Partial",evidence_linked:"Evidence Linked",needs_review:"Needs Review"};
const tones:Record<RequirementStatus,"neutral"|"danger"|"warning"|"good">={not_assessed:"neutral",missing:"danger",partial:"warning",evidence_linked:"good",needs_review:"warning"};

export default async function RegulatoryReportPage({params}:{params:Promise<{id:string}>}){const identity=await requireWorkspaceIdentity(),{id}=await params,report=await getRegulatoryReport(identity,id);if(!report)notFound();const {snapshot}=report;return <><PageHeader breadcrumbs={[{label:"Regulatory Navigator",href:"/app/regulatory"},{label:`${report.reportNumber} v${report.version}`}]} eyebrow="Regulatory Readiness Report" title={snapshot.profile.productName} description={`${snapshot.profile.projectCode} · ${snapshot.profile.projectName} · generated ${formatDate(report.createdAt)}`} actions={<><ButtonLink href={`/api/regulatory/reports/${report.id}/pdf`} external>Export PDF</ButtonLink><ButtonLink href={`/app/regulatory?profile=${snapshot.profile.id}`} variant="secondary">Back to Navigator</ButtonLink></>}/><RegulatoryDisclaimer/>
  <div className="record-summary-grid"><div className="record-summary"><span>Report</span><strong>{report.reportNumber} · Version {report.version}</strong></div><div className="record-summary"><span>Potential pathway</span><strong>{snapshot.assessment.possiblePathway}</strong></div><div className="record-summary"><span>Evidence coverage</span><strong>{snapshot.coverage.percentage}%</strong></div><div className="record-summary"><span>Ruleset</span><strong>{snapshot.assessment.ruleId} · {snapshot.assessment.ruleVersion}</strong></div></div>
  <Card><CardHeader title="1. Device overview"/><CardContent><dl className="detail-list"><div><dt>Product</dt><dd>{snapshot.profile.productName}</dd></div><div><dt>Intended user</dt><dd>{snapshot.profile.intendedUser}</dd></div><div><dt>Target population</dt><dd>{snapshot.profile.targetPopulation}</dd></div><div><dt>Clinical environment</dt><dd>{snapshot.profile.clinicalEnvironment}</dd></div><div><dt>Configuration</dt><dd>{snapshot.profile.deviceType}{snapshot.profile.isIVD?" · IVD":""}{snapshot.profile.isSaMD?" · SaMD":""}{snapshot.profile.hasAI?" · AI/ML":""}</dd></div></dl></CardContent></Card>
  <Card><CardHeader title="2. Intended use"/><CardContent><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{snapshot.profile.intendedUse}</p></CardContent></Card>
  <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader title="3. Target markets"/><CardContent><div className="flex gap-2">{snapshot.profile.markets.map((market)=><Badge key={market} tone={market==="US"?"info":"neutral"}>{market}{market==="EU"?" · Coming soon":""}</Badge>)}</div></CardContent></Card><Card><CardHeader title="4–5. Preliminary regulatory assessment"/><CardContent><dl className="detail-list"><div><dt>Device status</dt><dd>{snapshot.assessment.possibleDeviceStatus}</dd></div><div><dt>Classification</dt><dd>{snapshot.assessment.possibleClassification}</dd></div><div><dt>FDA pathway</dt><dd><strong>{snapshot.assessment.possiblePathway}</strong></dd></div></dl></CardContent></Card></div>
  <Card><CardHeader title="Why this preliminary result was produced" description={`${snapshot.assessment.ruleId} · version ${snapshot.assessment.ruleVersion}`}/><CardContent className="grid gap-5 lg:grid-cols-2"><div><h3 className="text-sm font-semibold text-slate-900">Reasoning</h3><ul className="mt-2 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-600">{snapshot.assessment.reasoning.map((item)=><li key={item}>{item}</li>)}</ul></div><div><h3 className="text-sm font-semibold text-slate-900">What must be confirmed</h3><ul className="mt-2 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-600">{snapshot.assessment.confirmations.map((item)=><li key={item}>{item}</li>)}</ul></div></CardContent></Card>
  <Card><CardHeader title="6. Evidence coverage"/><CardContent><div className="flex items-end justify-between"><strong className="text-3xl text-slate-950">{snapshot.coverage.percentage}%</strong><span className="text-sm text-slate-500">{snapshot.coverage.supported} supported · {snapshot.coverage.partial} partial · {snapshot.coverage.missing} missing</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-teal-600" style={{width:`${snapshot.coverage.percentage}%`}}/></div></CardContent></Card>
  <Card><CardHeader title="7. Evidence matrix" description="Links return to the organization-scoped LabOps source records."/><CardContent className="space-y-3">{snapshot.requirements.filter((item)=>item.status!=="not_assessed").map((item)=><div key={item.id} className="rounded-md border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-3"><strong className="min-w-0 flex-1 text-slate-950">{item.title}</strong><Badge tone={tones[item.status]}>{labels[item.status]}</Badge><Badge tone="neutral">{item.jurisdiction}</Badge></div><p className="mt-2 text-sm text-slate-600">{item.rationale}</p><div className="mt-3 flex flex-wrap gap-2">{item.evidence.map((evidence)=><Link key={evidence.id} href={evidence.href} className="inline-flex items-center gap-1 rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-teal-800 hover:border-teal-300">{evidence.label}<ExternalLink size={13}/></Link>)}{!item.evidence.length?<span className="text-xs text-slate-500">No evidence linked</span>:null}</div></div>)}</CardContent></Card>
  <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader title="8. Missing evidence"/><CardContent className="space-y-3">{snapshot.requirements.filter((item)=>item.status==="missing").map((item)=><div key={item.id} className="flex gap-3 rounded-md border border-red-200 bg-red-50 p-3"><AlertTriangle size={17} className="mt-0.5 text-red-700"/><div><strong className="text-sm text-red-950">{item.title}</strong><p className="mt-1 text-xs text-red-900">{item.description}</p></div></div>)}</CardContent></Card><Card><CardHeader title="9. Recommended next actions"/><CardContent><ol className="list-decimal space-y-2 pl-5 text-sm leading-6 text-slate-700">{snapshot.nextActions.map((item)=><li key={item}>{item}</li>)}</ol></CardContent></Card></div>
  <Card><CardHeader title="10. Assumptions"/><CardContent><ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-slate-600">{snapshot.assessment.assumptions.map((item)=><li key={item}>{item}</li>)}</ul></CardContent></Card>
  <Card><CardHeader title="Published framework references"/><CardContent className="space-y-2">{snapshot.references.map((reference)=><a key={reference.identifier} href={reference.sourceUrl} target="_blank" rel="noreferrer" className="block rounded-md border border-slate-200 p-3 text-sm text-teal-800 hover:border-teal-300"><strong>{reference.title}</strong><span className="block text-xs text-slate-500">{reference.authority} · {reference.identifier} · reviewed {reference.lastReviewedDate}</span></a>)}</CardContent></Card>
  <Card><CardHeader title="11. Disclaimer"/><CardContent><p className="text-sm leading-7 text-slate-700">{snapshot.disclaimer}</p><p className="mt-3 text-xs text-slate-500">This immutable snapshot records the assessment and evidence links as generated. It does not indicate FDA clearance, approval, compliance, validation, or legal submission readiness.</p></CardContent></Card>
  </>}
