import { BarChart3, FileCheck2, FileSpreadsheet, History, ShieldCheck, Sparkles } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";
import { marketingMetadata } from "@/lib/seo";

export const metadata = marketingMetadata({
  title: "Engineering Report Software",
  description: "Create evidence-linked engineering reports with optional AI-assisted drafting, transparent calculations, controlled revisions, and human review.",
  path: "/features/reports",
});
const items = [[FileSpreadsheet,"Evidence in context","Attach source files, select measured columns, and preserve the relationship between calculations and the record."],[BarChart3,"Transparent calculations","Descriptive statistics and criteria outcomes are deterministic and reviewable."],[Sparkles,"Guarded drafting","AI assistance is optional, labeled, constrained to supplied evidence, and never approves a result."],[History,"Revision history","Reports retain revision, author, reviewer, comments, and state transitions."],[FileCheck2,"Controlled PDF","Export the report, criteria, source notes, and review state as a readable record."],[ShieldCheck,"Role-aware review","Engineers draft; designated reviewers can request changes or approve a revision."]];
export default function ReportsFeaturePage(){return <div><section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-5xl px-5 py-20"><p className="text-sm font-semibold uppercase text-teal-800">Engineering report generator</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold text-slate-950">Turn test evidence into a report people can inspect.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">Build engineering test reports, inspection records, design reviews, and verification summaries without losing the source data, criteria, or human decisions behind them.</p><div className="mt-8 flex gap-3"><ButtonLink href="/signup">Start free trial</ButtonLink><ButtonLink href="/request-demo" variant="secondary">Discuss a pilot</ButtonLink></div></div></section><section id="guarded-ai" className="border-b border-violet-100 bg-violet-50/50"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-wide text-violet-700">Optional AI-assisted drafting</p><h2 className="mt-3 text-3xl font-semibold text-slate-950">A writing assistant—not a scientific authority.</h2></div><div className="grid gap-3 sm:grid-cols-2"><p className="rounded-lg border border-violet-100 bg-white p-4 text-sm leading-6 text-slate-600"><strong className="block text-slate-950">What it does</strong>Suggests executive summaries, methodology, results interpretation, and conclusions from supplied report evidence.</p><p className="rounded-lg border border-violet-100 bg-white p-4 text-sm leading-6 text-slate-600"><strong className="block text-slate-950">What it cannot do</strong>Change calculations, invent missing evidence, approve a report, sign a record, or replace engineering review.</p><p className="rounded-lg border border-violet-100 bg-white p-4 text-sm leading-6 text-slate-600"><strong className="block text-slate-950">How it is controlled</strong>Owners enable it per workspace, set monthly limits, and retain generation and acceptance history.</p><p className="rounded-lg border border-violet-100 bg-white p-4 text-sm leading-6 text-slate-600"><strong className="block text-slate-950">How text is saved</strong>A permitted user must review, may edit, checks an acceptance statement, and saves a visibly labeled section.</p></div></div></section><section className="mx-auto grid max-w-6xl gap-5 px-5 py-16 md:grid-cols-2">{items.map(([Icon,title,body])=><article key={String(title)} className="rounded-lg border border-slate-200 bg-white p-6"><Icon className="text-teal-700"/><h2 className="mt-5 text-lg font-semibold text-slate-950">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{String(body)}</p></article>)}</section></div>}
