"use client";

import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {AlertTriangle,CheckCircle2,Copy,Eye,LayoutTemplate,ListChecks,PenLine,Printer,RotateCcw,ShieldCheck,SlidersHorizontal,Sparkles,Table2} from "lucide-react";
import {saveQualityDocumentRevision} from "@/app/(workspace)/app/documents/actions";
import {Button} from "@/components/ui/button";
import {DocumentPreview} from "@/components/documents/document-preview";

type AiResponse={suggestion?:string;promptVersion?:string;model?:string;generatedAt?:string;dlp?:{blocked:boolean;redacted:boolean;findings:{category:string;severity:string;count:number}[]};error?:string};
type DraftGoal="full_draft"|"review_ready"|"table_forward"|"operator_friendly";
const promptStarters=[
  {label:"Add evidence tables",icon:Table2,text:"Use clear Markdown tables for evidence links, responsibilities, acceptance criteria, open items, and approval status where appropriate."},
  {label:"Make it review-ready",icon:ListChecks,text:"Add reviewer questions, a completeness checklist, decision points, assumptions, and explicit evidence placeholders."},
  {label:"Help a new engineer",icon:LayoutTemplate,text:"Use plain language, short instructions, examples, and section-level guidance suitable for an entry-level engineer."},
] as const;

export function QualityDocumentEditor({documentId,title,revision,initialContent,locked,configured}:{documentId:string;title:string;revision:number;initialContent:string;locked:boolean;configured:boolean}){
  const router=useRouter(),[content,setContent]=useState(initialContent),[source,setSource]=useState<"user"|"ai_assisted">("user"),[metadata,setMetadata]=useState<AiResponse|null>(null),[reviewed,setReviewed]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[generating,setGenerating]=useState(false),[pending,startTransition]=useTransition(),[view,setView]=useState<"write"|"preview">("write"),[prompt,setPrompt]=useState(""),[goal,setGoal]=useState<DraftGoal>("full_draft"),[detail,setDetail]=useState<"concise"|"standard"|"detailed">("detailed"),[audience,setAudience]=useState<"engineering"|"quality"|"regulatory"|"cross_functional">("cross_functional"),[undoContent,setUndoContent]=useState<string|null>(null),[copied,setCopied]=useState(false);
  async function generate(){setGenerating(true);setError("");setNotice("");try{const response=await fetch("/api/ai/quality-document",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId,localContent:content,customInstruction:prompt,goal,detail,audience})});const data=await response.json() as AiResponse;if(!response.ok)throw new Error(data.error??"AI document generation failed.");setUndoContent(content);setContent(data.suggestion??content);setSource("ai_assisted");setMetadata(data);setReviewed(false);setView("preview");setNotice(data.dlp?.redacted?"AI draft created after sensitive identifiers in your instruction were redacted. Review every field before saving.":"AI draft created from public document metadata and your screened instruction. Review every field before saving.");}catch(cause){setError(cause instanceof Error?cause.message:"AI document generation failed.");}finally{setGenerating(false);}}
  function save(){setError("");setNotice("");startTransition(async()=>{try{await saveQualityDocumentRevision({documentId,content,source,model:metadata?.model,promptVersion:metadata?.promptVersion,generatedAt:metadata?.generatedAt,dlpSummary:metadata?.dlp?JSON.stringify(metadata.dlp):undefined});setSource("user");setMetadata(null);setReviewed(false);setNotice("New controlled revision saved.");router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Revision could not be saved.");}});}
  async function copyMarkdown(){await navigator.clipboard.writeText(content);setCopied(true);setTimeout(()=>setCopied(false),1800);}
  return <div className="space-y-4">
    {!locked?<section className="ai-composer"><div className="ai-composer-heading"><span className="ai-composer-icon"><Sparkles size={20}/></span><div><p>LabOps AI document architect</p><h3>Describe the document you want to build</h3><span>Your draft stays local. Only public template metadata and the screened instruction below are sent to AI.</span></div><span className="ai-private-badge"><ShieldCheck size={14}/>DLP protected</span></div>
      <div className="ai-prompt-starters" aria-label="Prompt starters">{promptStarters.map((starter)=>{const Icon=starter.icon;return <button key={starter.label} type="button" onClick={()=>setPrompt(starter.text)}><Icon size={15}/>{starter.label}</button>})}</div>
      <label className="ai-prompt-box"><span>Prompt the document architect</span><textarea value={prompt} onChange={(event)=>setPrompt(event.target.value)} rows={4} maxLength={1500} placeholder="Example: Create a detailed plan for a cross-functional team. Include RACI responsibilities, stage-gate outputs, evidence tables, measurable completion criteria, and reviewer questions. Keep all project facts as [TBD]."/><small>{prompt.length.toLocaleString()} / 1,500 · Do not include patient data, secrets, product identifiers, or confidential results.</small></label>
      <div className="ai-controls"><label><span>Drafting goal</span><select value={goal} onChange={(event)=>setGoal(event.target.value as DraftGoal)}><option value="full_draft">Build a complete rough draft</option><option value="review_ready">Prepare a reviewer-focused draft</option><option value="table_forward">Create a structured, table-forward draft</option><option value="operator_friendly">Make it easy for a new engineer</option></select></label><label><span>Detail</span><select value={detail} onChange={(event)=>setDetail(event.target.value as typeof detail)}><option value="concise">Concise</option><option value="standard">Standard</option><option value="detailed">Detailed</option></select></label><label><span>Primary reader</span><select value={audience} onChange={(event)=>setAudience(event.target.value as typeof audience)}><option value="cross_functional">Cross-functional team</option><option value="engineering">Engineering</option><option value="quality">Quality</option><option value="regulatory">Regulatory</option></select></label></div>
      <div className="ai-composer-footer"><p><SlidersHorizontal size={15}/>AI builds an editable rough draft, never an approval or compliance determination.</p><Button type="button" onClick={generate} disabled={!configured||generating||pending}><Sparkles size={17}/>{generating?"Architecting document…":"Generate guided draft"}</Button></div>
    </section>:null}
    <div className="document-view-toolbar"><div role="group" aria-label="Document view"><button type="button" aria-pressed={view==="write"} onClick={()=>setView("write")}><PenLine size={16}/>Write</button><button type="button" aria-pressed={view==="preview"} onClick={()=>setView("preview")}><Eye size={16}/>Beautiful preview</button></div><div>{undoContent!==null&&!locked?<button type="button" onClick={()=>{setContent(undoContent);setUndoContent(null);setSource("user");setMetadata(null);setReviewed(false);setView("write");}}><RotateCcw size={15}/>Undo AI change</button>:null}<button type="button" onClick={copyMarkdown}><Copy size={15}/>{copied?"Copied":"Copy Markdown"}</button>{view==="preview"?<button type="button" onClick={()=>window.print()}><Printer size={15}/>Print</button>:null}</div></div>
    {view==="write"?<label className="form-field"><span>Controlled document content</span><textarea rows={28} value={content} onChange={(event)=>{setContent(event.target.value);if(source==="ai_assisted")setReviewed(false);}} disabled={locked} maxLength={100000} className="document-source-editor"/><small>{content.length.toLocaleString()} / 100,000 characters · Markdown headings, lists, tables, callouts, bold text, and [TBD] fields are styled in preview.</small></label>:<DocumentPreview title={title} content={content} revision={revision}/>}
    {error?<p role="alert" className="flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"><AlertTriangle size={18}/>{error}</p>:null}{notice?<p role="status" className="flex gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900"><CheckCircle2 size={18}/>{notice}</p>:null}
    {source==="ai_assisted"?<label className="flex items-start gap-3 rounded-lg border border-violet-200 bg-violet-50/60 p-4 text-sm leading-6"><input type="checkbox" className="mt-1 size-4 min-h-0" checked={reviewed} onChange={(event)=>setReviewed(event.target.checked)}/><span>I reviewed and edited this AI-generated rough template, verified its content against source evidence, and accept authorship responsibility. It remains unapproved until independent review.</span></label>:null}
    {!locked?<div className="flex flex-wrap justify-end gap-3 border-t border-slate-200 pt-4"><Button type="button" onClick={save} disabled={pending||content.trim().length<10||(source==="ai_assisted"&&!reviewed)}>{pending?"Saving controlled revision…":"Save new revision"}</Button></div>:null}
    {!configured&&!locked?<p className="text-sm text-amber-800">An administrator must configure and enable AI assistance before template generation is available. Manual editing still works.</p>:null}
  </div>;
}
