import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { getWorkspaceIdentity } from "@/lib/auth";
import { getRegulatoryReport } from "@/lib/data/regulatory";
import { enforceRateLimit } from "@/lib/security/rate-limit";
import { createAdminClient } from "@/lib/supabase/admin";

function wrap(text:string,max=88){const words=text.replace(/\s+/g," ").trim().split(" "),lines:string[]=[];let line="";for(const word of words){if(`${line} ${word}`.trim().length>max){if(line)lines.push(line);line=word;}else line=`${line} ${word}`.trim();}if(line)lines.push(line);return lines;}

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const identity=await getWorkspaceIdentity();if(!identity)return NextResponse.json({error:"Authentication required"},{status:401});if(!identity.demo){const limit=await enforceRateLimit(`${identity.organizationId}:${identity.userId}`,"regulatory_pdf_export",30,3600);if(!limit.allowed)return NextResponse.json({error:"PDF export limit reached"},{status:429});}const{id}=await params,report=await getRegulatoryReport(identity,id);if(!report)return NextResponse.json({error:"Regulatory report not found"},{status:404});const {snapshot}=report,pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),teal=rgb(.04,.38,.36),muted=rgb(.35,.4,.48);let page=pdf.addPage([612,792]),y=742,pageNumber=1;
  const footer=()=>{page.drawText(`MicroCD LabOps · ${report.reportNumber} v${report.version} · Page ${pageNumber}`,{x:54,y:28,size:8,font:regular,color:muted});};
  const newPage=()=>{footer();page=pdf.addPage([612,792]);pageNumber+=1;y=742;};
  const draw=(value:string,options:{size?:number;font?:typeof regular;color?:ReturnType<typeof rgb>;gap?:number;indent?:number}={})=>{const size=options.size??10;for(const line of wrap(String(value),size>14?62:options.indent?82:92)){if(y<62)newPage();page.drawText(line,{x:54+(options.indent??0),y,size,font:options.font??regular,color:options.color??rgb(.12,.16,.22)});y-=size+5;}y-=options.gap??4;};
  draw("MICROCD LABOPS · DECISION SUPPORT",{size:9,font:bold,color:teal,gap:10});draw("Regulatory Readiness Report",{size:20,font:bold,gap:5});draw(`${snapshot.profile.productName} · ${report.reportNumber} · Version ${report.version}`,{size:10,color:muted,gap:12});draw(`Project: ${snapshot.profile.projectCode} · ${snapshot.profile.projectName}`);draw(`Generated: ${snapshot.generatedAt} by ${snapshot.generatedBy}`,{gap:14});draw("IMPORTANT DISCLAIMER",{size:11,font:bold,color:rgb(.7,.25,.05)});draw(snapshot.disclaimer,{size:9,gap:16});
  draw("1. Device overview",{size:13,font:bold,color:teal});draw(`Product: ${snapshot.profile.productName}`);draw(`Intended user: ${snapshot.profile.intendedUser}`);draw(`Target population: ${snapshot.profile.targetPopulation}`);draw(`Clinical environment: ${snapshot.profile.clinicalEnvironment}`,{gap:10});draw("2. Intended use",{size:13,font:bold,color:teal});draw(snapshot.profile.intendedUse,{gap:10});draw("3. Target markets",{size:13,font:bold,color:teal});draw(snapshot.profile.markets.join(" + "),{gap:10});draw("4–5. Preliminary regulatory assessment",{size:13,font:bold,color:teal});draw(`Potential device status: ${snapshot.assessment.possibleDeviceStatus}`);draw(`Potential classification: ${snapshot.assessment.possibleClassification}`);draw(`Possible pathway: ${snapshot.assessment.possiblePathway}`);draw(`Rule: ${snapshot.assessment.ruleId} · version ${snapshot.assessment.ruleVersion}`,{color:muted,gap:8});for(const item of snapshot.assessment.reasoning)draw(`• ${item}`,{indent:8,size:9,gap:2});draw("What should be confirmed",{size:11,font:bold,gap:3});for(const item of snapshot.assessment.confirmations)draw(`• ${item}`,{indent:8,size:9,gap:2});y-=8;
  draw("6. Evidence coverage",{size:13,font:bold,color:teal});draw(`${snapshot.coverage.percentage}% coverage · ${snapshot.coverage.supported} supported · ${snapshot.coverage.partial} partial · ${snapshot.coverage.missing} missing`,{gap:10});draw("7. Evidence matrix",{size:13,font:bold,color:teal});for(const requirement of snapshot.requirements.filter((item)=>item.status!=="not_assessed")){draw(`${requirement.status.replaceAll("_"," ").toUpperCase()} · ${requirement.title}`,{font:bold,size:9,gap:2});draw(requirement.rationale,{size:8,gap:2,indent:8});for(const evidence of requirement.evidence)draw(`Source: ${evidence.label} (${evidence.href})`,{size:8,color:muted,indent:8,gap:2});y-=3;}
  draw("8. Missing evidence",{size:13,font:bold,color:teal});for(const item of snapshot.requirements.filter((requirement)=>requirement.status==="missing"))draw(`• ${item.title}: ${item.description}`,{size:9,indent:8,gap:2});draw("9. Recommended next actions",{size:13,font:bold,color:teal});snapshot.nextActions.forEach((item,index)=>draw(`${index+1}. ${item}`,{size:9,indent:8,gap:2}));draw("10. Assumptions",{size:13,font:bold,color:teal});for(const item of snapshot.assessment.assumptions)draw(`• ${item}`,{size:9,indent:8,gap:2});draw("11. Disclaimer",{size:13,font:bold,color:teal});draw(snapshot.disclaimer,{size:9});footer();const bytes=await pdf.save();if(!identity.demo)await createAdminClient().from("activity_log").insert({organization_id:identity.organizationId,actor_id:identity.userId,action:"regulatory_report_exported",record_type:"Regulatory readiness report",record_id:report.id,summary:`PDF exported for ${report.reportNumber} version ${report.version}`});return new NextResponse(Buffer.from(bytes),{headers:{"Content-Type":"application/pdf","Content-Disposition":`inline; filename="${report.reportNumber}-v${report.version}.pdf"`,"Cache-Control":"private, no-store"}});}
