import { CheckCircle2, FlaskConical, Rocket, Sparkles } from "lucide-react";
import { applyWorkspaceTemplate } from "../growth-actions";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { SubmitButton } from "@/components/ui/submit-button";
import { requireWorkspaceIdentity } from "@/lib/auth";
import { listAppliedTemplates } from "@/lib/data/growth";
import { workspaceTemplates } from "@/lib/growth-capabilities";

export default async function GetStartedPage({searchParams}:{searchParams:Promise<{applied?:string}>}){const identity=await requireWorkspaceIdentity();const params=await searchParams;const applied=await listAppliedTemplates(identity);return <><PageHeader eyebrow="Faster time to first workflow" title="Workspace templates" description="Create a coherent starter project, protocol, and task plan—then adapt it to what customer discovery shows." actions={<Badge tone="info">Editable after creation</Badge>}/>{params.applied?<div className="mb-5 flex gap-3 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-emerald-900"><CheckCircle2 size={18}/><div><strong>Starter workflow created</strong><p className="mt-1 text-sm">Open Projects, Protocols, and Tasks to tailor it to the pilot.</p></div></div>:null}<div className="grid gap-5 lg:grid-cols-3">{workspaceTemplates.map((template,index)=>{const used=applied.includes(template.key);return <Card key={template.key} className={index===0?"ring-2 ring-teal-600/20":""}><CardHeader title={template.name} description={template.audience} action={used?<Badge tone="good">Applied</Badge>:index===0?<Badge tone="info">Popular</Badge>:undefined}/><CardContent><span className="grid size-11 place-items-center rounded-xl bg-teal-50 text-teal-800">{index===0?<FlaskConical/>:index===1?<Sparkles/>:<Rocket/>}</span><p className="mt-5 text-sm leading-6 text-slate-600">{template.description}</p><div className="mt-5 rounded-lg bg-slate-50 p-4 text-sm"><strong className="text-slate-950">Creates</strong><ul className="mt-2 space-y-2 text-slate-600"><li>1 starter project</li><li>1 versioned draft protocol</li><li>3 assigned setup tasks</li></ul></div>{!identity.demo&&!used?<form action={applyWorkspaceTemplate} className="mt-5"><input type="hidden" name="templateKey" value={template.key}/><SubmitButton idle="Apply template" pending="Creating workflow…" className="w-full"/></form>:<p className="mt-5 text-center text-xs font-semibold text-slate-500">{identity.demo?"Template application is disabled in the demo.":"This template is already in your workspace."}</p>}</CardContent></Card>})}</div></>}
